# Last Change: Mon Nov 03 06:00 PM 2008 J
# vim:syntax=python
from os.path import join
from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)

env.NumpyPythonExtension('ckdtree', source = ['ckdtree.c'])

env.NumpyPythonExtension('_distance_wrap', 
                         source = [join('src', 'distance_wrap.c'),
                                   join('src', 'distance.c')])

# Build qhull
src = [pjoin('qhull', 'src', s) for s in [
    'geom.c', 'geom2.c', 'global.c', 'io.c', 'mem.c',
    'merge.c', 'poly.c', 'poly2.c', 'qset.c', 'user.c',
    'stat.c', 'qhull.c']]
qhullsrc = env.DistutilsStaticExtLibrary('qhullsrc', source=src)

env.NumpyPythonExtension('qhull', source = 'qhull.c', LIBS="qhullsrc")
