# Last Change: Wed Mar 05 05:00 PM 2008 J
# vim:syntax=python
from os.path import join

from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)

env.NumpyPythonExtension('sigtools', 
                         source = ['sigtoolsmodule.c',\
                                   'firfilter.c', \
                                   'medianfilter.c'])

env.NumpyPythonExtension('spline', 
                         source = ['splinemodule.c', 'S_bspline_util.c', 
                                   'D_bspline_util.c', 'C_bspline_util.c', 
                                   'Z_bspline_util.c','bspline_util.c'])
