# Last Change: Mon Apr 20 04:00 PM 2009 J
# vim:syntax=python
from os.path import join

from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)

src = env.FromCTemplate("lfilter.c.src")
src += env.FromCTemplate("correlate_nd.c.src")
env.NumpyPythonExtension('sigtools', 
                         source = src + ['sigtoolsmodule.c',\
                                   'firfilter.c', \
                                   'medianfilter.c'])

env.NumpyPythonExtension('spectral', source='spectral.c')

env.NumpyPythonExtension('spline', 
                         source = ['splinemodule.c', 'S_bspline_util.c', 
                                   'D_bspline_util.c', 'C_bspline_util.c', 
                                   'Z_bspline_util.c','bspline_util.c'])
