# Last Change: Sat Nov 24 07:00 PM 2007 J
# vim:syntax=python
from os.path import join

from numpy.distutils.misc_util import get_numpy_include_dirs
from numpy.distutils.scons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)

env.AppendUnique(CPPPATH = get_numpy_include_dirs())
env.NumpyPythonExtension('sigtools', 
                         source = ['sigtoolsmodule.c',\
                                   'firfilter.c', \
                                   'medianfilter.c'])

env.NumpyPythonExtension('spline', 
                         source = ['splinemodule.c', 'S_bspline_util.c', 
                                   'D_bspline_util.c', 'C_bspline_util.c', 
                                   'Z_bspline_util.c','bspline_util.c'])
