# This module exists only to allow Sphinx to generate docs
# for the result objects returned by some functions in stats
# _without_ adding them to the main stats documentation page.

"""
Errors
------

.. currentmodule:: scipy.stats._warnings_errors

.. autosummary::
   :toctree: generated/

   FitError
   FitDataError
   FitSolverError

Warnings
--------

.. currentmodule:: scipy.stats._warnings_errors

.. autosummary::
   :toctree: generated/

   BootstrapDegenerateDistributionWarning
   F_onewayConstantInputWarning
   F_onewayBadInputSizesWarning
   PearsonRConstantInputWarning
   PearsonRNearConstantInputWarning
   SpearmanRConstantInputWarning

"""

from scipy.stats import (F_onewayConstantInputWarning,
                         F_onewayBadInputSizesWarning,
                         PearsonRConstantInputWarning,
                         PearsonRNearConstantInputWarning,
                         SpearmanRConstantInputWarning)


# Warnings


class SciPyStatsWarning(RuntimeWarning):
    """Represents a runtime warning specific to `scipy.stats`."""
    def __init__(self, msg=None):
        if msg is None:
            msg = ("A runtime warning occured in `scipy.stats`.")
        self.args = (msg,)


class BootstrapDegenerateDistributionWarning(SciPyStatsWarning):
    """
    Warning generated by `bootstrap` when BCa method is used and
    the bootstrap distribution is degenerate.
    """

    def __init__(self, msg=None):
        if msg is None:
            msg = ("The bootstrap distribution is degenerate; the "
                   "confidence interval is not defined.")
        self.args = (msg,)

# Errors


class SciPyStatsError(RuntimeError):
    """Represents a runtime error specific to `scipy.stats`."""
    def __init__(self, msg=None):
        if msg is None:
            msg = ("A runtime error occured in `scipy.stats`.")
        self.args = (msg,)


class FitError(SciPyStatsError):
    """Represents an error condition when fitting a distribution to data."""
    def __init__(self, msg=None):
        if msg is None:
            msg = ("A runtime error occured when fitting a distribution to "
                   "data.")
        self.args = (msg,)


class FitDataError(ValueError):
    """Raised when data is inconsistent with fixed parameters."""
    # This exception is raised by, for example, beta_gen.fit when both floc
    # and fscale are fixed and there are values in the data not in the open
    # interval (floc, floc+fscale).
    def __init__(self, distr, lower, upper):
        self.args = (
            "Invalid values in `data`.  Maximum likelihood "
            "estimation with {distr!r} requires that {lower!r} < "
            "(x - loc)/scale  < {upper!r} for each x in `data`.".format(
                distr=distr, lower=lower, upper=upper),
        )


class FitSolverError(RuntimeError):
    """
    Raised when a solver fails to converge while fitting a distribution.
    """
    # This exception is raised by, for example, beta_gen.fit when
    # optimize.fsolve returns with ier != 1.
    def __init__(self, mesg):
        emsg = "Solver for the MLE equations failed to converge: "
        emsg += mesg.replace('\n', '')
        self.args = (emsg,)
