# This file contains globs for automatically adding labels based on changed files,
# for use with https://github.com/actions/labeler.

scipy.cluster:
- changed-files:
  - any-glob-to-any-file:
    - scipy/cluster/**

scipy.constants:
- changed-files:
  - any-glob-to-any-file:
    - scipy/constants/**

scipy.differentiate:
- changed-files:
  - any-glob-to-any-file:
    - scipy/differentiate/**

scipy.fft:
- changed-files:
  - any-glob-to-any-file:
    - scipy/fft/**

scipy.fftpack:
- changed-files:
  - any-glob-to-any-file:
    - scipy/fftpack/**

scipy.integrate:
- changed-files:
  - any-glob-to-any-file:
    - scipy/integrate/**

scipy.interpolate:
- changed-files:
  - any-glob-to-any-file:
    - scipy/interpolate/**

scipy.io:
- changed-files:
  - any-glob-to-any-file:
    - scipy/io/**

scipy._lib:
- changed-files:
  - any-glob-to-any-file:
    - scipy/_lib/**

scipy.linalg:
- changed-files:
  - any-glob-to-any-file:
    - scipy/linalg/**

scipy.ndimage:
- changed-files:
  - any-glob-to-any-file:
    - scipy/ndimage/**

scipy.odr:
- changed-files:
  - any-glob-to-any-file:
    - scipy/odr/**

scipy.optimize:
- changed-files:
  - any-glob-to-any-file:
    - scipy/optimize/**

scipy.signal:
- changed-files:
  - any-glob-to-any-file:
    - scipy/signal/**

scipy.sparse:
- changed-files:
  - all-globs-to-any-file:
    - scipy/sparse/**
    # don't match the `csgraph` or `linalg` submodules
    - '!scipy/sparse/csgraph/**'
    - '!scipy/sparse/linalg/**'

scipy.sparse.csgraph:
- changed-files:
  - any-glob-to-any-file:
    - scipy/sparse/csgraph/**

scipy.sparse.linalg:
- changed-files:
  - any-glob-to-any-file:
    - scipy/sparse/linalg/**

scipy.spatial:
- changed-files:
  - any-glob-to-any-file:
    - scipy/spatial/**

scipy.special:
- changed-files:
  - any-glob-to-any-file:
    - scipy/special/**

scipy.stats:
- changed-files:
  - any-glob-to-any-file:
    - scipy/stats/**

Cython:
- changed-files:
  - any-glob-to-any-file:
    - scipy/**/*.pyx*
    - scipy/**/*.pxd*
    - scipy/**/*.pxi*
    - scipy/**/_generate_pyx.py

Fortran:
- changed-files:
  - any-glob-to-any-file:
    - scipy/**/*.f
    - scipy/**/*.f.src
    - scipy/**/*.F
    - scipy/**/*.f90
    - scipy/**/*.pyf

C/C++:
- changed-files:
  - any-glob-to-any-file:
    - scipy/**/*.c
    - scipy/**/*.c.in
    - scipy/**/*.c.old
    - scipy/**/*.h
    - scipy/**/*.h.in
    - scipy/**/*.cpp
    - scipy/**/*.cc
    - scipy/**/*.cxx
    - scipy/**/*.hpp

array types:
- changed-files:
  - any-glob-to-any-file:
    - scipy/_lib/_array_api.py

Meson:
- changed-files:
  - any-glob-to-any-file:
    - scipy/**/meson.build
    - meson.build

Documentation:
- changed-files:
  - any-glob-to-any-file:
    - doc/**

CI:
- changed-files:
  - any-glob-to-any-file:
    - .circleci/**
    - .github/workflows/**
    - ci/**
    - .cirrus.star

DX:
- changed-files:
  - any-glob-to-any-file:
    - doc/source/dev/**

Build issues:
- changed-files:
  - any-glob-to-any-file:
    - scipy/_build_utils/**

uarray:
- changed-files:
  - any-glob-to-any-file:
    - scipy/_lib/_uarray/**
    - scipy/_lib/uarray.py
