scipy.cluster:
- scipy/cluster/**/*

scipy.constants:
- scipy/constants/**/*

scipy.fft:
- scipy/fft/**/*

scipy.fftpack:
- scipy/fftpack/**/*

scipy.integrate:
- scipy/integrate/**/*

scipy.interpolate:
- scipy/interpolate/**/*

scipy.io:
- scipy/io/**/*

scipy._lib:
- scipy/_lib/**/*

scipy.linalg:
- scipy/linalg/**/*

scipy.misc:
- scipy/misc/**/*

scipy.ndimage:
- scipy/ndimage/**/*

scipy.odr:
- scipy/odr/**/*

scipy.optimize:
- scipy/optimize/**/*

scipy.signal:
- scipy/signal/**/*

scipy.sparse:
- all: ["scipy/sparse/**/*", "!scipy/sparse/csgraph/**/*", "!scipy/sparse/linalg/**/*"]

scipy.sparse.csgraph:
- scipy/sparse/csgraph/**/*

scipy.sparse.linalg:
- scipy/sparse/linalg/**/*

scipy.spatial:
- scipy/spatial/**/*

scipy.special:
- scipy/special/**/*

scipy.stats:
- scipy/stats/**/*

scipy.weave:
- scipy/weave/**/*

Cython:
- scipy/**/*.pyx.*
- scipy/**/*.pxd.*
- scipy/**/*.pxi.*

Fortran:
- scipy/**/*.f
- scipy/**/*.f.src
- scipy/**/*.F
- scipy/**/*.f90

C/C++:
- scipy/**/*.c
- scipy/**/*.c.in
- scipy/**/*.c.old
- scipy/**/*.h
- scipy/**/*.h.in
- scipy/**/*.cpp
- scipy/**/*.cc
- scipy/**/*.cxx
- scipy/**/*.hpp
