Cython:
- scipy/**/*.pyx.*
- scipy/**/*.pxd.*
- scipy/**/*.pxi.*

Fortran:
- scipy/**/*.f
- scipy/**/*.f.src
- scipy/**/*.F
- scipy/**/*.f90

C/C++:
- scipy/**/*.c
- scipy/**/*.c.in
- scipy/**/*.c.old
- scipy/**/*.h
- scipy/**/*.h.in
- scipy/**/*.cpp
- scipy/**/*.cc
- scipy/**/*.cxx
- scipy/**/*.hpp
