# This file contains regexes for automatically adding labels to PRs which have been merged.
# for use with https://github.com/github/issue-labeler.

# Add the needs-release-note-decision tag to PRs that typically require a
# mention in the release notes.
needs-release-note-decision:
  - 'ENH'
  - 'DEP'
