superlu_config = configure_file(
  input: 'src/SuperLU/SRC/superlu_config.h.in',
  output: 'superlu_config.h',
  format: 'cmake@',
  configuration: configuration_data(),
)

_superlu_lib_c_args = ['-DUSE_VENDOR_BLAS=1']
if is_windows
  _superlu_lib_c_args += ['-DNO_TIMER=1']
endif
_superlu_lib_c_args += [
  Wno_unused_variable,
  Wno_parentheses,
  Wno_unused_label,
  Wno_implicit_function_declaration,
  Wno_switch,
  Wno_unused_result,
  Wno_maybe_uninitialized,
]
superlu_lib = static_library('superlu_lib',
  [
    'src/SuperLU/SRC/ccolumn_bmod.c',
    'src/SuperLU/SRC/ccolumn_dfs.c',
    'src/SuperLU/SRC/ccopy_to_ucol.c',
    'src/SuperLU/SRC/cdiagonal.c',
    'src/SuperLU/SRC/cgscon.c',
    'src/SuperLU/SRC/cgsequ.c',
    'src/SuperLU/SRC/cgsisx.c',
    'src/SuperLU/SRC/cgsitrf.c',
    'src/SuperLU/SRC/cgsrfs.c',
    'src/SuperLU/SRC/cgssv.c',
    'src/SuperLU/SRC/cgssvx.c',
    'src/SuperLU/SRC/cgstrf.c',
    'src/SuperLU/SRC/cgstrs.c',
    'src/SuperLU/SRC/clacon2.c',
    'src/SuperLU/SRC/clangs.c',
    'src/SuperLU/SRC/claqgs.c',
    'src/SuperLU/SRC/cldperm.c',
    'src/SuperLU/SRC/cmemory.c',
    'src/SuperLU/SRC/cmyblas2.c',
    'src/SuperLU/SRC/colamd.c',
    'src/SuperLU/SRC/cpanel_bmod.c',
    'src/SuperLU/SRC/cpanel_dfs.c',
    'src/SuperLU/SRC/cpivotL.c',
    'src/SuperLU/SRC/cpivotgrowth.c',
    'src/SuperLU/SRC/cpruneL.c',
    'src/SuperLU/SRC/creadMM.c',
    'src/SuperLU/SRC/creadhb.c',
    'src/SuperLU/SRC/creadrb.c',
    'src/SuperLU/SRC/creadtriple.c',
    'src/SuperLU/SRC/csnode_bmod.c',
    'src/SuperLU/SRC/csnode_dfs.c',
    'src/SuperLU/SRC/csp_blas2.c',
    'src/SuperLU/SRC/csp_blas3.c',
    'src/SuperLU/SRC/cutil.c',
    'src/SuperLU/SRC/dGetDiagU.c',
    'src/SuperLU/SRC/dcolumn_bmod.c',
    'src/SuperLU/SRC/dcolumn_dfs.c',
    'src/SuperLU/SRC/dcomplex.c',
    'src/SuperLU/SRC/dcopy_to_ucol.c',
    'src/SuperLU/SRC/ddiagonal.c',
    'src/SuperLU/SRC/dgscon.c',
    'src/SuperLU/SRC/dgsequ.c',
    'src/SuperLU/SRC/dgsisx.c',
    'src/SuperLU/SRC/dgsitrf.c',
    'src/SuperLU/SRC/dgsrfs.c',
    'src/SuperLU/SRC/dgssv.c',
    'src/SuperLU/SRC/dgssvx.c',
    'src/SuperLU/SRC/dgstrf.c',
    'src/SuperLU/SRC/dgstrs.c',
    'src/SuperLU/SRC/dlacon2.c',
    'src/SuperLU/SRC/dlangs.c',
    'src/SuperLU/SRC/dlaqgs.c',
    'src/SuperLU/SRC/dldperm.c',
    'src/SuperLU/SRC/dmach.c',
    'src/SuperLU/SRC/dmemory.c',
    'src/SuperLU/SRC/dmyblas2.c',
    'src/SuperLU/SRC/dpanel_bmod.c',
    'src/SuperLU/SRC/dpanel_dfs.c',
    'src/SuperLU/SRC/dpivotL.c',
    'src/SuperLU/SRC/dpivotgrowth.c',
    'src/SuperLU/SRC/dpruneL.c',
    'src/SuperLU/SRC/dreadMM.c',
    'src/SuperLU/SRC/dreadhb.c',
    'src/SuperLU/SRC/dreadrb.c',
    'src/SuperLU/SRC/dreadtriple.c',
    'src/SuperLU/SRC/dsnode_bmod.c',
    'src/SuperLU/SRC/dsnode_dfs.c',
    'src/SuperLU/SRC/dsp_blas2.c',
    'src/SuperLU/SRC/dsp_blas3.c',
    'src/SuperLU/SRC/dutil.c',
    'src/SuperLU/SRC/dzsum1.c',
    'src/SuperLU/SRC/get_perm_c.c',
    'src/SuperLU/SRC/heap_relax_snode.c',
    'src/SuperLU/SRC/icmax1.c',
    'src/SuperLU/SRC/ilu_ccolumn_dfs.c',
    'src/SuperLU/SRC/ilu_ccopy_to_ucol.c',
    'src/SuperLU/SRC/ilu_cdrop_row.c',
    'src/SuperLU/SRC/ilu_cpanel_dfs.c',
    'src/SuperLU/SRC/ilu_cpivotL.c',
    'src/SuperLU/SRC/ilu_csnode_dfs.c',
    'src/SuperLU/SRC/ilu_dcolumn_dfs.c',
    'src/SuperLU/SRC/ilu_dcopy_to_ucol.c',
    'src/SuperLU/SRC/ilu_ddrop_row.c',
    'src/SuperLU/SRC/ilu_dpanel_dfs.c',
    'src/SuperLU/SRC/ilu_dpivotL.c',
    'src/SuperLU/SRC/ilu_dsnode_dfs.c',
    'src/SuperLU/SRC/ilu_heap_relax_snode.c',
    'src/SuperLU/SRC/ilu_relax_snode.c',
    'src/SuperLU/SRC/ilu_scolumn_dfs.c',
    'src/SuperLU/SRC/ilu_scopy_to_ucol.c',
    'src/SuperLU/SRC/ilu_sdrop_row.c',
    'src/SuperLU/SRC/ilu_spanel_dfs.c',
    'src/SuperLU/SRC/ilu_spivotL.c',
    'src/SuperLU/SRC/ilu_ssnode_dfs.c',
    'src/SuperLU/SRC/ilu_zcolumn_dfs.c',
    'src/SuperLU/SRC/ilu_zcopy_to_ucol.c',
    'src/SuperLU/SRC/ilu_zdrop_row.c',
    'src/SuperLU/SRC/ilu_zpanel_dfs.c',
    'src/SuperLU/SRC/ilu_zpivotL.c',
    'src/SuperLU/SRC/ilu_zsnode_dfs.c',
    'src/SuperLU/SRC/input_error.c',
    'src/SuperLU/SRC/izmax1.c',
    'src/SuperLU/SRC/mark_relax.c',
    'src/SuperLU/SRC/memory.c',
    'src/SuperLU/SRC/mmd.c',
    'src/SuperLU/SRC/qselect.c',
    'src/SuperLU/SRC/relax_snode.c',
    'src/SuperLU/SRC/scolumn_bmod.c',
    'src/SuperLU/SRC/scolumn_dfs.c',
    'src/SuperLU/SRC/scomplex.c',
    'src/SuperLU/SRC/scopy_to_ucol.c',
    'src/SuperLU/SRC/scsum1.c',
    'src/SuperLU/SRC/sdiagonal.c',
    'src/SuperLU/SRC/sgscon.c',
    'src/SuperLU/SRC/sgsequ.c',
    'src/SuperLU/SRC/sgsisx.c',
    'src/SuperLU/SRC/sgsitrf.c',
    'src/SuperLU/SRC/sgsrfs.c',
    'src/SuperLU/SRC/sgssv.c',
    'src/SuperLU/SRC/sgssvx.c',
    'src/SuperLU/SRC/sgstrf.c',
    'src/SuperLU/SRC/sgstrs.c',
    'src/SuperLU/SRC/slacon2.c',
    'src/SuperLU/SRC/slangs.c',
    'src/SuperLU/SRC/slaqgs.c',
    'src/SuperLU/SRC/sldperm.c',
    'src/SuperLU/SRC/smach.c',
    'src/SuperLU/SRC/smemory.c',
    'src/SuperLU/SRC/smyblas2.c',
    'src/SuperLU/SRC/sp_coletree.c',
    'src/SuperLU/SRC/sp_ienv.c',
    'src/SuperLU/SRC/sp_preorder.c',
    'src/SuperLU/SRC/spanel_bmod.c',
    'src/SuperLU/SRC/spanel_dfs.c',
    'src/SuperLU/SRC/spivotL.c',
    'src/SuperLU/SRC/spivotgrowth.c',
    'src/SuperLU/SRC/spruneL.c',
    'src/SuperLU/SRC/sreadMM.c',
    'src/SuperLU/SRC/sreadhb.c',
    'src/SuperLU/SRC/sreadrb.c',
    'src/SuperLU/SRC/sreadtriple.c',
    'src/SuperLU/SRC/ssnode_bmod.c',
    'src/SuperLU/SRC/ssnode_dfs.c',
    'src/SuperLU/SRC/ssp_blas2.c',
    'src/SuperLU/SRC/ssp_blas3.c',
    'src/SuperLU/SRC/superlu_timer.c',
    'src/SuperLU/SRC/sutil.c',
    'src/SuperLU/SRC/util.c',
    'src/SuperLU/SRC/zcolumn_bmod.c',
    'src/SuperLU/SRC/zcolumn_dfs.c',
    'src/SuperLU/SRC/zcopy_to_ucol.c',
    'src/SuperLU/SRC/zdiagonal.c',
    'src/SuperLU/SRC/zgscon.c',
    'src/SuperLU/SRC/zgsequ.c',
    'src/SuperLU/SRC/zgsisx.c',
    'src/SuperLU/SRC/zgsitrf.c',
    'src/SuperLU/SRC/zgsrfs.c',
    'src/SuperLU/SRC/zgssv.c',
    'src/SuperLU/SRC/zgssvx.c',
    'src/SuperLU/SRC/zgstrf.c',
    'src/SuperLU/SRC/zgstrs.c',
    'src/SuperLU/SRC/zlacon2.c',
    'src/SuperLU/SRC/zlangs.c',
    'src/SuperLU/SRC/zlaqgs.c',
    'src/SuperLU/SRC/zldperm.c',
    'src/SuperLU/SRC/zmemory.c',
    'src/SuperLU/SRC/zmyblas2.c',
    'src/SuperLU/SRC/zpanel_bmod.c',
    'src/SuperLU/SRC/zpanel_dfs.c',
    'src/SuperLU/SRC/zpivotL.c',
    'src/SuperLU/SRC/zpivotgrowth.c',
    'src/SuperLU/SRC/zpruneL.c',
    'src/SuperLU/SRC/zreadMM.c',
    'src/SuperLU/SRC/zreadhb.c',
    'src/SuperLU/SRC/zreadrb.c',
    'src/SuperLU/SRC/zreadtriple.c',
    'src/SuperLU/SRC/zsnode_bmod.c',
    'src/SuperLU/SRC/zsnode_dfs.c',
    'src/SuperLU/SRC/zsp_blas2.c',
    'src/SuperLU/SRC/zsp_blas3.c',
    'src/SuperLU/SRC/zutil.c',
    superlu_config,
  ],
  c_args: _superlu_lib_c_args,
  dependencies: [blas_dep],
  include_directories: ['src', 'src/SuperLU/SRC'],
  gnu_symbol_visibility: 'hidden',
)

py3.extension_module('_superlu',
  ['src/_superlumodule.c', 'src/_superlu_utils.c', 'src/_superluobject.c'],
  link_with: [superlu_lib],
  include_directories: ['src', 'src/SuperLU/SRC'],
  link_args: version_link_args,
  dependencies: [blas_dep, np_dep],
  install: true,
  subdir: 'scipy/sparse/linalg/_dsolve'
)

py3.install_sources([
    '__init__.py',
    '_add_newdocs.py',
    'linsolve.py'
  ],
  subdir: 'scipy/sparse/linalg/_dsolve'
)

subdir('tests')
