runners:
  - name: scipy-onprem-gpu
    cloud: on_prem
    instance_type: 12vcpu-48gb-100gb
    machine_image: "ubuntu-gpu:latest"
    region: RegionOne
    labels:
      - cirun-scipy-onprem-gpu
    extra_config:
      executor: meda
      gpu: all
      cache: true
