runners:
  - name: gpu-runner
    cloud: aws
    instance_type: g5.8xlarge
    machine_image: ami-014cf2391cb36896e
    region: eu-west-1
    labels:
      - cirun-aws-gpu
    extra_config:
      cache: true
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          VolumeType: gp3
          VolumeSize: 100
          Iops: 16000
          Throughput: 1000
