codecov:
  require_ci_to_pass: false
  notify:
    require_ci_to_pass: no
    after_n_builds: 1
coverage:
  status:
    project:
      default:
        # Require 1% coverage, i.e., always succeed
        target: 1
    patch:
      default:
        # Must be 0%, because many PRs touch files that we don't have coverage
        # results for (build files, scripts, tools/, etc.)
        target: 0
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
    changes: false
comment: off
github_checks:
    annotations: false
