codecov:
  require_ci_to_pass: false
  notify:
    require_ci_to_pass: no
    after_n_builds: 1
coverage:
  status:
    project:
      default:
        # Require 1% coverage, i.e., always succeed
        target: 1
    patch:
      default:
        target: 90
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: failure
    changes: false
comment: off
