[mypy]
warn_redundant_casts = True
show_error_codes = True

local_partial_types = True
allow_redefinition_new = true

# Typing tests is low priority, but enabling type checking on the
# untyped test functions is still high-value because it helps test the
# typing.

[mypy-scipy.special.tests.test_orthogonal]
check_untyped_defs = True

[mypy-scipy.special.tests.test_sf_error]
check_untyped_defs = True

[mypy-scipy.spatial.tests.test_spherical_voronoi]
check_untyped_defs = True

# Vendored code

[mypy-scipy._external.array_api_compat.*]
ignore_errors = True

[mypy-scipy._external.array_api_extra.*]
ignore_errors = True

[mypy-scipy._external.pyprima.*]
ignore_errors = True

# Third party dependencies that don't have types.

[mypy-cython]
ignore_missing_imports = True

[mypy-mpmath]
ignore_missing_imports = True

[mypy-pooch]
ignore_missing_imports = True

[mypy-pytest_run_parallel]
ignore_missing_imports = True

[mypy-pytest_timeout]
ignore_missing_imports = True

[mypy-scipy_doctest.*]
ignore_missing_imports = True

[mypy-threadpoolctl]
ignore_missing_imports = True

# Third party dependencies that can't be found

[mypy-scikits.*]
ignore_missing_imports = True

[mypy-sksparse.*]
ignore_missing_imports = True

[mypy-sparse]
ignore_missing_imports = True

[mypy-sympy.*]
ignore_missing_imports = True

[mypy-uarray]
ignore_missing_imports = True

# Typed, but cumbersome to install
# e.g. depend on SciPy, or not available on Windows

[mypy-cupyx.*]
ignore_missing_imports = True

[mypy-jax]
ignore_missing_imports = True

# Extension modules without stubs.

[mypy-scipy._lib._ccallback_c]
ignore_missing_imports = True

[mypy-scipy._lib._fpumode]
ignore_missing_imports = True

[mypy-scipy._lib.*]
ignore_missing_imports = True

[mypy-scipy.cluster.hierarchy._hierarchy]
ignore_missing_imports = True

[mypy-scipy.fft._duccfft.pyduccfft]
ignore_missing_imports = True

[mypy-scipy.integrate._test_multivariate]
ignore_missing_imports = True

[mypy-scipy.integrate._odepack]
ignore_missing_imports = True

[mypy-scipy.interpolate._dierckx]
ignore_missing_imports = True

[mypy-scipy.interpolate._interpnd]
ignore_missing_imports = True

[mypy-scipy.interpolate._rbfinterp_pythran]
ignore_missing_imports = True

[mypy-scipy.interpolate._rgi_cython]
ignore_missing_imports = True

[mypy-scipy.io.matlab._mio5_utils]
ignore_missing_imports = True

[mypy-scipy.io.matlab._mio_utils]
ignore_missing_imports = True

[mypy-scipy.io.matlab._streams]
ignore_missing_imports = True

[mypy-scipy.linalg.cython_blas]
ignore_missing_imports = True

[mypy-scipy.linalg._batched_linalg]
ignore_missing_imports = True

[mypy-scipy.linalg._decomp_interpolative]
ignore_missing_imports = True

[mypy-scipy.linalg._decomp_update]
ignore_missing_imports = True

[mypy-scipy.linalg._fblas]
ignore_missing_imports = True

[mypy-scipy.linalg._fblas_64]
ignore_missing_imports = True

[mypy-scipy.linalg._flapack]
ignore_missing_imports = True

[mypy-scipy.linalg._flapack_64]
ignore_missing_imports = True

[mypy-scipy.linalg._internal_matfuncs]
ignore_missing_imports = True

[mypy-scipy.linalg._matfuncs_sqrtm_triu]
ignore_missing_imports = True

[mypy-scipy.linalg._solve_toeplitz]
ignore_missing_imports = True

[mypy-scipy.optimize._highspy._core]
ignore_missing_imports = True

[mypy-scipy.optimize._lsq.givens_elimination]
ignore_missing_imports = True

[mypy-scipy.optimize._trlib._trlib]
ignore_missing_imports = True

[mypy-scipy.optimize._bglu_dense]
ignore_missing_imports = True

[mypy-scipy.optimize._group_columns]
ignore_missing_imports = True

[mypy-scipy.optimize._lsap]
ignore_missing_imports = True

[mypy-scipy.optimize._pava_pybind]
ignore_missing_imports = True

[mypy-scipy.optimize._slsqplib]
ignore_missing_imports = True

[mypy-scipy.signal._max_len_seq_inner]
ignore_missing_imports = True

[mypy-scipy.signal._peak_finding_utils]
ignore_missing_imports = True

[mypy-scipy.signal._sosfilt]
ignore_missing_imports = True

[mypy-scipy.signal._upfirdn_apply]
ignore_missing_imports = True

[mypy-scipy.sparse._sparsetools]
ignore_missing_imports = True

[mypy-scipy.sparse.csgraph._flow]
ignore_missing_imports = True

[mypy-scipy.sparse.csgraph._matching]
ignore_missing_imports = True

[mypy-scipy.sparse.csgraph._min_spanning_tree]
ignore_missing_imports = True

[mypy-scipy.sparse.csgraph._reordering]
ignore_missing_imports = True

[mypy-scipy.sparse.csgraph._shortest_path]
ignore_missing_imports = True

[mypy-scipy.sparse.csgraph._tools]
ignore_missing_imports = True

[mypy-scipy.sparse.csgraph._traversal]
ignore_missing_imports = True

[mypy-scipy.sparse.linalg._dsolve._superlu]
ignore_missing_imports = True

[mypy-scipy.spatial.transform._rigid_transform_cy]
ignore_missing_imports = True

[mypy-scipy.spatial.transform._rotation_cy]
ignore_missing_imports = True

[mypy-scipy.spatial._ckdtree]
ignore_missing_imports = True

[mypy-scipy.special._ellip_harm_2]
ignore_missing_imports = True

[mypy-scipy.special._gufuncs]
ignore_missing_imports = True

[mypy-scipy.special._special_ufuncs]
ignore_missing_imports = True

[mypy-scipy.stats._levy_stable.levyst]
ignore_missing_imports = True

[mypy-scipy.stats._rcont.rcont]
ignore_missing_imports = True

[mypy-scipy.stats._ansari_swilk_statistics]
ignore_missing_imports = True

[mypy-scipy.stats._biasedurn]
ignore_missing_imports = True

[mypy-scipy.stats._qmvnt_cy]
ignore_missing_imports = True

[mypy-scipy.stats._stats]
ignore_missing_imports = True

[mypy-scipy.stats._stats_pythran]
ignore_missing_imports = True

# Files referencing compiled code that needs stubs added.

[mypy-scipy._lib.tests.test_ccallback]
disable_error_code = attr-defined

[mypy-scipy.fftpack._pseudo_diffs]
disable_error_code = attr-defined

[mypy-scipy.integrate._ode]
disable_error_code = attr-defined

[mypy-scipy.integrate._quadpack_py]
disable_error_code = attr-defined

[mypy-scipy.interpolate.tests.test_bsplines]
disable_error_code = attr-defined

[mypy-scipy.interpolate.tests.test_interpolate]
disable_error_code = attr-defined

[mypy-scipy.interpolate._bsplines]
disable_error_code = attr-defined

[mypy-scipy.interpolate._fitpack_impl]
disable_error_code = attr-defined

[mypy-scipy.interpolate._interpolate]
disable_error_code = attr-defined

[mypy-scipy.linalg.tests.test_cython_lapack]
disable_error_code = attr-defined

[mypy-scipy.ndimage.tests.test_c_api]
disable_error_code = attr-defined

[mypy-scipy.ndimage.tests.test_filters]
disable_error_code = attr-defined

[mypy-scipy.ndimage.tests.test_fourier]
disable_error_code = attr-defined

[mypy-scipy.ndimage._filters]
disable_error_code = attr-defined

[mypy-scipy.ndimage._fourier]
disable_error_code = attr-defined

[mypy-scipy.ndimage._interpolation]
disable_error_code = attr-defined

[mypy-scipy.ndimage._measurements]
disable_error_code = attr-defined

[mypy-scipy.ndimage._morphology]
disable_error_code = attr-defined

[mypy-scipy.optimize._lsq.least_squares]
disable_error_code = attr-defined

[mypy-scipy.optimize.tests.test_cython_optimize]
disable_error_code = attr-defined

[mypy-scipy.optimize.tests.test_lbfgsb_setulb]
disable_error_code = attr-defined

[mypy-scipy.optimize._remove_redundancy]
disable_error_code = attr-defined

[mypy-scipy.optimize._zeros_py]
disable_error_code = attr-defined

[mypy-scipy.optimize._tnc]
disable_error_code = attr-defined

[mypy-scipy.optimize._lbfgsb_py]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_windows]
disable_error_code = attr-defined

[mypy-scipy.signal._fir_filter_design]
disable_error_code = attr-defined

[mypy-scipy.signal._signal_api]
disable_error_code = attr-defined

[mypy-scipy.signal._signaltools]
disable_error_code = attr-defined

[mypy-scipy.sparse.linalg._eigen.arpack.arpack]
disable_error_code = attr-defined

[mypy-scipy.sparse.linalg._isolve._gcrotmk]
disable_error_code = attr-defined

[mypy-scipy.spatial.tests.test_distance]
disable_error_code = attr-defined

[mypy-scipy.spatial.tests.test_kdtree]
disable_error_code = attr-defined

[mypy-scipy.spatial.transform.tests.test_rotation_groups]
disable_error_code = attr-defined

[mypy-scipy.special.tests.test_boost_ufuncs]
disable_error_code = attr-defined

[mypy-scipy.special._basic]
disable_error_code = attr-defined

[mypy-scipy.stats.tests.test_continuous_fit_censored]
disable_error_code = attr-defined

[mypy-scipy.stats.tests.test_multivariate]
disable_error_code = attr-defined

[mypy-scipy.stats.tests.test_discrete_distns]
disable_error_code = attr-defined

[mypy-scipy.stats.tests.test_discrete_basic]
disable_error_code = attr-defined

[mypy-scipy.stats._mstats_extras]
disable_error_code = attr-defined

# Files referencing missing attributes in `{signal,ndimage}.__all__`

[mypy-scipy.signal.tests._scipy_spectral_test_shim]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_cont2discrete]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_czt]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_dltisys]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_filter_design]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_fir_filter_design]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_ltisys]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_max_len_seq]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_result_type]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_savitzky_golay]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_short_time_fft]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_signaltools]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_spectral]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_splines]
disable_error_code = attr-defined

[mypy-scipy.signal.tests.test_upfirdn]
disable_error_code = attr-defined

# Setting dunders on under-typed callables

[mypy-scipy.fft._helper]
disable_error_code = attr-defined

[mypy-scipy.fft._duccfft.basic]
disable_error_code = attr-defined

[mypy-scipy.fft._duccfft.realtransforms]
disable_error_code = attr-defined

# Files with various errors. Likely some false positives, but likely
# some real bugs too.

[mypy-scipy.optimize.tests.test_nonlin]
# setting attributes on a function;
# could fix by using a `dataclass`
disable_error_code = attr-defined

[mypy-scipy.optimize._minpack_py]
# false positive?
# scipy/optimize/_minpack_py.py:14: error: Name "least_squares" already defined (by an import)  [no-redef]
disable_error_code = no-redef,attr-defined

[mypy-scipy.sparse.linalg._eigen.tests.test_svds]
ignore_errors = True

[mypy-scipy.sparse.linalg._isolve.tests.test_gcrotmk]
ignore_errors = True

[mypy-scipy.sparse.linalg._isolve.tests.test_lgmres]
ignore_errors = True

[mypy-scipy.sparse.tests.test_base]
ignore_errors = True

[mypy-scipy.sparse._csr]
ignore_errors = True

[mypy-scipy.sparse._dok]
ignore_errors = True

[mypy-scipy.sparse._sputils]
ignore_errors = True

[mypy-scipy.stats.tests.test_continuous_basic]
ignore_errors = True

[mypy-scipy.stats.tests.test_distributions]
disable_error_code = attr-defined

[mypy-scipy.stats.tests.test_rank]
ignore_errors = True

[mypy-scipy.stats.tests.test_qmc]
ignore_errors = True

[mypy-scipy.stats._discrete_distns]
ignore_errors = True

[mypy-scipy.stats._multivariate]
ignore_errors = True

[mypy-scipy.stats._qmc]
ignore_errors = True

[mypy-scipy.stats._stats_py]
ignore_errors = True

[mypy-scipy.stats.distributions]
ignore_errors = True
