# 'Tox' is a tool for automating sdist/build/test cycles against
# multiple Python versions:
#   https://pypi.python.org/pypi/tox
#   https://tox.readthedocs.io

# Running the command 'tox' while in the root of the SciPy source
# directory will:
#   - Create a SciPy source distribution (setup.py sdist)
#   - Then for every supported version of Python:
#     - Create a virtualenv in {homedir}/.tox/scipy/py$VERSION and
#       install dependencies. (These virtualenvs are cached across
#       runs unless you use --recreate.)
#     - Use pip to install the SciPy sdist into the virtualenv
#     - Run the SciPy tests
# To run against a specific subset of Python versions, use:
#   tox -e py36,py37

# Extra arguments will be passed to test-installed-scipy.py. To run
# the full testsuite:
#   tox full
# To run with extra verbosity:
#   tox -- -v

# Tox assumes that you have appropriate Python interpreters already
# installed and that they can be run as 'python3.6', 'python3.7', etc.

[tox]
envlist = py37,py38,py39
skipsdist=True

[testenv]
deps=
    pytest
    numpy
    cython
    pybind11
changedir={envdir}
commands=
    {envpython} {toxinidir}/runtests.py {posargs: --mode full}

[pycodestyle]
max_line_length = 88
statistics = True
ignore = E121,E122,E123,E125,E126,E127,E128,E226,E231,E251,E265,E266,E302,E402,E501,E712,E721,E731,E741,W291,W293,W391,W503,W504
exclude = scipy/__config__.py

[flake8]
# max line length for black
max-line-length = 88
target-version = ['py37']
# Default flake8 3.5 ignored flags
ignore=
    E24,   # check ignored by default in flake8. Meaning unclear.
    E121,  # continuation line under-indented
    E123,  # closing bracket does not match indentation
    E126,  # continuation line over-indented for hanging indent
    E203,  # space before : (needed for how black formats slicing)
    E226,  # missing whitespace around arithmetic operator
    E704,  # multiple statements on one line (def)
    E731,  # do not assign a lambda expression, use a def
    E741,  # do not use variables named ‘l’, ‘O’, or ‘I’
    W503,  # line break before binary operator
    W504,  # line break after binary operator
    E401,  # imported but unused
    E402,  # module level import not at top of file
    E501,  # line too long (in docstrings: math, links) done by black
exclude=
    .git,
    __pycache__,
    scipy/__init__.py,
    scipy/*/__init__.py,
    benchmarks/benchmarks/go_benchmark_functions/__init__.py,
    dist,
    doc/build,
    doc/source/conf.py,
    doc/source/tutorial,
    build
    setup.py
