# distutils: language=c++
# cython: language_level=3

'''Export enum values and constants from HiGHS.'''

from HConst cimport (
    HIGHS_CONST_I_INF,
    HIGHS_CONST_INF,
)
from HighsIO cimport (
    ML_NONE,
    ML_VERBOSE,
    ML_DETAILED,
    ML_MINIMAL,
    ML_ALWAYS,
)
from HighsLp cimport (
    HighsModelStatusNOTSET,
    HighsModelStatusLOAD_ERROR,
    HighsModelStatusMODEL_ERROR,
    HighsModelStatusMODEL_EMPTY,
    HighsModelStatusPRESOLVE_ERROR,
    HighsModelStatusSOLVE_ERROR,
    HighsModelStatusPOSTSOLVE_ERROR,
    HighsModelStatusPRIMAL_INFEASIBLE,
    HighsModelStatusPRIMAL_UNBOUNDED,
    HighsModelStatusOPTIMAL,
    HighsModelStatusREACHED_DUAL_OBJECTIVE_VALUE_UPPER_BOUND,
    HighsModelStatusREACHED_TIME_LIMIT,
    HighsModelStatusREACHED_ITERATION_LIMIT,
)


# HConst
CONST_I_INF = HIGHS_CONST_I_INF
CONST_INF = HIGHS_CONST_INF

# HighsIO
MESSAGE_LEVEL_NONE = ML_NONE
MESSAGE_LEVEL_VERBOSE = ML_VERBOSE
MESSAGE_LEVEL_DETAILED = ML_DETAILED
MESSAGE_LEVEL_MINIMAL = ML_MINIMAL
MESSAGE_LEVEL_ALWAYS = ML_ALWAYS

# HighsLp
MODEL_STATUS_NOTSET = <int> HighsModelStatusNOTSET
MODEL_STATUS_LOAD_ERROR = <int> HighsModelStatusLOAD_ERROR
MODEL_STATUS_MODEL_ERROR = <int> HighsModelStatusMODEL_ERROR
MODEL_STATUS_MODEL_EMPTY = <int> HighsModelStatusMODEL_EMPTY
MODEL_STATUS_PRESOLVE_ERROR = <int> HighsModelStatusPRESOLVE_ERROR
MODEL_STATUS_SOLVE_ERROR = <int> HighsModelStatusSOLVE_ERROR
MODEL_STATUS_POSTSOLVE_ERROR = <int> HighsModelStatusPOSTSOLVE_ERROR
MODEL_STATUS_PRIMAL_INFEASIBLE = <int> HighsModelStatusPRIMAL_INFEASIBLE
MODEL_STATUS_PRIMAL_UNBOUNDED = <int> HighsModelStatusPRIMAL_UNBOUNDED
MODEL_STATUS_OPTIMAL = <int> HighsModelStatusOPTIMAL
MODEL_STATUS_REACHED_DUAL_OBJECTIVE_VALUE_UPPER_BOUND = <int> HighsModelStatusREACHED_DUAL_OBJECTIVE_VALUE_UPPER_BOUND
MODEL_STATUS_REACHED_TIME_LIMIT = <int> HighsModelStatusREACHED_TIME_LIMIT
MODEL_STATUS_REACHED_ITERATION_LIMIT = <int> HighsModelStatusREACHED_ITERATION_LIMIT
