name: Blank Template
description: Create your own issue

body:
  - type: input
    attributes:
      label: Please describe your issue.
      description: 'If your issue is not in one of the template categories you can add a free form description of it here.'
    validations:
      required: true
