name: Bug Report
description: Create a report to help us improve SciPy
title: "BUG: "
labels: [defect]

body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to file a bug report.
  - type: markdown
    attributes:
        value: Before continuing, please check the issue tracker for existing issues and the [development documentation](https://scipy.github.io/devdocs/index.html). Your issue could be already fixed on the development version. If you have an installation problem, make sure that you are following the [latest installation recommendations](https://scipy.github.io/devdocs/dev/contributor/contributor_toc.html#development-environment).
  - type: textarea
    attributes:
      label: Describe your issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproducing Code Example
      description: 'Paste the Reproducing code example and it will be rendered as a code block.'
      render: python
    validations:
      required: true
  - type: textarea
    attributes:
      label: Error message
      description: 'If any, paste the *full* error message as above (starting from line Traceback) and it will be rendered as a code block'
      render: shell
    validations:
      required: true
  - type: input
    attributes:
      label: SciPy/NumPy/Python version information
      description: 'Please run the following and paste the result in a code block - `import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)`'
    validations:
      required: true
