blank_issues_enabled: true
contact_links:
    about: Ask questions and discuss with other scipy community members
  - name: Stack Overflow
    url: https://stackoverflow.com/questions/tagged/scipy
    about: Please ask and answer usage questions on Stack Overflow
  - name: User Mailing list
    url: https://mail.python.org/mailman3/lists/scipy-user.python.org/
    about: User-related questions and announcements on the mailing list
  - name: Developer Mailing list
    url: https://mail.python.org/mailman3/lists/scipy-dev.python.org/
    about: Development discussions and announcements on the mailing list
  - name: Blank issue
    url: https://github.com/scipy/scipy/issues/new
    about: Please note that other templates should be used in most cases
