name: Documentation
description: Report an issue related to the SciPy documentation.
title: "DOC: <Please write a comprehensive title after the 'DOC: ' prefix>"
labels: [Documentation]

body:
- type: textarea
  attributes: 
    label: "Issue with current documentation:"
    description: >
      Please check the development version of the documentation at
      https://scipy.github.io/devdocs/ to see if this issue has already been
      addressed. If not, please link to the development version (either using
      the link above or selecting the dev version in the documentation version
      dropdown) of the document/code you're referring to.

- type: textarea
  attributes:
    label: "Idea or request for content:"
    description: >
      Please describe as clearly as possible a suggested fix, better phrasing or
      topics you think are missing from the current documentation.

- type: textarea
  attributes:
    label: Additional context (e.g. screenshots, GIFs)
