# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_bsr', [dirname(__file__)])
        except ImportError:
            import _bsr
            return _bsr
        if fp is not None:
            try:
                _mod = imp.load_module('_bsr', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _bsr = swig_import_helper()
    del swig_import_helper
else:
    import _bsr
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def bsr_diagonal(*args):
  """
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper const [] Ax, npy_bool_wrapper [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char const [] Ax, signed char [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char const [] Ax, unsigned char [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        short const [] Ax, short [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short const [] Ax, unsigned short [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        int const [] Ax, int [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int const [] Ax, unsigned int [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long const [] Ax, long long [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long const [] Ax, unsigned long long [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        float const [] Ax, float [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        double const [] Ax, double [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double const [] Ax, long double [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper const [] Ax, npy_cfloat_wrapper [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper const [] Ax, npy_cdouble_wrapper [] Yx)
    bsr_diagonal(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper const [] Ax, npy_clongdouble_wrapper [] Yx)
    """
  return _bsr.bsr_diagonal(*args)

def bsr_scale_rows(*args):
  """
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper [] Ax, npy_bool_wrapper const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char [] Ax, signed char const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char [] Ax, unsigned char const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        short [] Ax, short const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short [] Ax, unsigned short const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        int [] Ax, int const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int [] Ax, unsigned int const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long [] Ax, long long const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long [] Ax, unsigned long long const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        float [] Ax, float const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        double [] Ax, double const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double [] Ax, long double const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper [] Ax, npy_cfloat_wrapper const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper [] Ax, npy_cdouble_wrapper const [] Xx)
    bsr_scale_rows(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper [] Ax, npy_clongdouble_wrapper const [] Xx)
    """
  return _bsr.bsr_scale_rows(*args)

def bsr_scale_columns(*args):
  """
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper [] Ax, npy_bool_wrapper const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char [] Ax, signed char const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char [] Ax, unsigned char const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        short [] Ax, short const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short [] Ax, unsigned short const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        int [] Ax, int const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int [] Ax, unsigned int const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long [] Ax, long long const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long [] Ax, unsigned long long const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        float [] Ax, float const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        double [] Ax, double const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double [] Ax, long double const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper [] Ax, npy_cfloat_wrapper const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper [] Ax, npy_cdouble_wrapper const [] Xx)
    bsr_scale_columns(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper [] Ax, npy_clongdouble_wrapper const [] Xx)
    """
  return _bsr.bsr_scale_columns(*args)

def bsr_transpose(*args):
  """
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper const [] Ax, int [] Bp, int [] Bj, npy_bool_wrapper [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char const [] Ax, int [] Bp, int [] Bj, signed char [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char const [] Ax, int [] Bp, int [] Bj, unsigned char [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        short const [] Ax, int [] Bp, int [] Bj, short [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short const [] Ax, int [] Bp, int [] Bj, unsigned short [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        int const [] Ax, int [] Bp, int [] Bj, int [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int const [] Ax, int [] Bp, int [] Bj, unsigned int [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long const [] Ax, int [] Bp, int [] Bj, long long [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long const [] Ax, int [] Bp, int [] Bj, unsigned long long [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        float const [] Ax, int [] Bp, int [] Bj, float [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        double const [] Ax, int [] Bp, int [] Bj, double [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double const [] Ax, int [] Bp, int [] Bj, long double [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper const [] Ax, int [] Bp, int [] Bj, npy_cfloat_wrapper [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper const [] Ax, int [] Bp, int [] Bj, npy_cdouble_wrapper [] Bx)
    bsr_transpose(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper const [] Ax, int [] Bp, int [] Bj, npy_clongdouble_wrapper [] Bx)
    """
  return _bsr.bsr_transpose(*args)

def bsr_matmat_pass2(*args):
  """
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, npy_bool_wrapper const [] Ax, int const [] Bp, 
        int const [] Bj, npy_bool_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, signed char const [] Ax, int const [] Bp, int const [] Bj, 
        signed char const [] Bx, int [] Cp, int [] Cj, signed char [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, unsigned char const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned char const [] Bx, int [] Cp, int [] Cj, unsigned char [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, short const [] Ax, int const [] Bp, int const [] Bj, 
        short const [] Bx, int [] Cp, int [] Cj, short [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, unsigned short const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned short const [] Bx, int [] Cp, int [] Cj, unsigned short [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, int const [] Ax, int const [] Bp, int const [] Bj, 
        int const [] Bx, int [] Cp, int [] Cj, int [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, unsigned int const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned int const [] Bx, int [] Cp, int [] Cj, unsigned int [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, long long const [] Ax, int const [] Bp, int const [] Bj, 
        long long const [] Bx, int [] Cp, int [] Cj, long long [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, unsigned long long const [] Ax, int const [] Bp, 
        int const [] Bj, unsigned long long const [] Bx, int [] Cp, int [] Cj, unsigned long long [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, float const [] Ax, int const [] Bp, int const [] Bj, 
        float const [] Bx, int [] Cp, int [] Cj, float [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, double const [] Ax, int const [] Bp, int const [] Bj, 
        double const [] Bx, int [] Cp, int [] Cj, double [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, long double const [] Ax, int const [] Bp, int const [] Bj, 
        long double const [] Bx, int [] Cp, int [] Cj, long double [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, npy_cfloat_wrapper const [] Ax, int const [] Bp, 
        int const [] Bj, npy_cfloat_wrapper const [] Bx, int [] Cp, int [] Cj, npy_cfloat_wrapper [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, npy_cdouble_wrapper const [] Ax, int const [] Bp, 
        int const [] Bj, npy_cdouble_wrapper const [] Bx, int [] Cp, int [] Cj, 
        npy_cdouble_wrapper [] Cx)
    bsr_matmat_pass2(int const n_brow, int const n_bcol, int const R, int const C, int const N, int const [] Ap, 
        int const [] Aj, npy_clongdouble_wrapper const [] Ax, int const [] Bp, 
        int const [] Bj, npy_clongdouble_wrapper const [] Bx, int [] Cp, int [] Cj, 
        npy_clongdouble_wrapper [] Cx)
    """
  return _bsr.bsr_matmat_pass2(*args)

def bsr_matvec(*args):
  """
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper const [] Ax, npy_bool_wrapper const [] Xx, 
        npy_bool_wrapper [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char const [] Ax, signed char const [] Xx, signed char [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char const [] Ax, unsigned char const [] Xx, unsigned char [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        short const [] Ax, short const [] Xx, short [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short const [] Ax, unsigned short const [] Xx, unsigned short [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        int const [] Ax, int const [] Xx, int [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int const [] Ax, unsigned int const [] Xx, unsigned int [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long const [] Ax, long long const [] Xx, long long [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long const [] Ax, unsigned long long const [] Xx, 
        unsigned long long [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        float const [] Ax, float const [] Xx, float [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        double const [] Ax, double const [] Xx, double [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double const [] Ax, long double const [] Xx, long double [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper const [] Ax, npy_cfloat_wrapper const [] Xx, 
        npy_cfloat_wrapper [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper const [] Ax, npy_cdouble_wrapper const [] Xx, 
        npy_cdouble_wrapper [] Yx)
    bsr_matvec(int const n_brow, int const n_bcol, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper const [] Ax, npy_clongdouble_wrapper const [] Xx, 
        npy_clongdouble_wrapper [] Yx)
    """
  return _bsr.bsr_matvec(*args)

def bsr_matvecs(*args):
  """
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, npy_bool_wrapper const [] Ax, npy_bool_wrapper const [] Xx, 
        npy_bool_wrapper [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, signed char const [] Ax, signed char const [] Xx, 
        signed char [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, unsigned char const [] Ax, unsigned char const [] Xx, 
        unsigned char [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, short const [] Ax, short const [] Xx, short [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, unsigned short const [] Ax, unsigned short const [] Xx, 
        unsigned short [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, int const [] Ax, int const [] Xx, int [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, unsigned int const [] Ax, unsigned int const [] Xx, 
        unsigned int [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, long long const [] Ax, long long const [] Xx, 
        long long [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, unsigned long long const [] Ax, unsigned long long const [] Xx, 
        unsigned long long [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, float const [] Ax, float const [] Xx, float [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, double const [] Ax, double const [] Xx, double [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, long double const [] Ax, long double const [] Xx, 
        long double [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, npy_cfloat_wrapper const [] Ax, npy_cfloat_wrapper const [] Xx, 
        npy_cfloat_wrapper [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, npy_cdouble_wrapper const [] Ax, npy_cdouble_wrapper const [] Xx, 
        npy_cdouble_wrapper [] Yx)
    bsr_matvecs(int const n_brow, int const n_bcol, int const n_vecs, int const R, int const C, int const [] Ap, 
        int const [] Aj, npy_clongdouble_wrapper const [] Ax, npy_clongdouble_wrapper const [] Xx, 
        npy_clongdouble_wrapper [] Yx)
    """
  return _bsr.bsr_matvecs(*args)

def bsr_elmul_bsr(*args):
  """
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_bool_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char const [] Ax, int const [] Bp, int const [] Bj, signed char const [] Bx, 
        int [] Cp, int [] Cj, signed char [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char const [] Ax, int const [] Bp, int const [] Bj, unsigned char const [] Bx, 
        int [] Cp, int [] Cj, unsigned char [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        short const [] Ax, int const [] Bp, int const [] Bj, short const [] Bx, 
        int [] Cp, int [] Cj, short [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned short const [] Bx, int [] Cp, int [] Cj, unsigned short [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        int const [] Ax, int const [] Bp, int const [] Bj, int const [] Bx, 
        int [] Cp, int [] Cj, int [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int const [] Ax, int const [] Bp, int const [] Bj, unsigned int const [] Bx, 
        int [] Cp, int [] Cj, unsigned int [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long const [] Ax, int const [] Bp, int const [] Bj, long long const [] Bx, 
        int [] Cp, int [] Cj, long long [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned long long const [] Bx, int [] Cp, int [] Cj, unsigned long long [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        float const [] Ax, int const [] Bp, int const [] Bj, float const [] Bx, 
        int [] Cp, int [] Cj, float [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        double const [] Ax, int const [] Bp, int const [] Bj, double const [] Bx, 
        int [] Cp, int [] Cj, double [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double const [] Ax, int const [] Bp, int const [] Bj, long double const [] Bx, 
        int [] Cp, int [] Cj, long double [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cfloat_wrapper const [] Bx, int [] Cp, int [] Cj, npy_cfloat_wrapper [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_cdouble_wrapper [] Cx)
    bsr_elmul_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_clongdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_clongdouble_wrapper [] Cx)
    """
  return _bsr.bsr_elmul_bsr(*args)

def bsr_eldiv_bsr(*args):
  """
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_bool_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char const [] Ax, int const [] Bp, int const [] Bj, signed char const [] Bx, 
        int [] Cp, int [] Cj, signed char [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char const [] Ax, int const [] Bp, int const [] Bj, unsigned char const [] Bx, 
        int [] Cp, int [] Cj, unsigned char [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        short const [] Ax, int const [] Bp, int const [] Bj, short const [] Bx, 
        int [] Cp, int [] Cj, short [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned short const [] Bx, int [] Cp, int [] Cj, unsigned short [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        int const [] Ax, int const [] Bp, int const [] Bj, int const [] Bx, 
        int [] Cp, int [] Cj, int [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int const [] Ax, int const [] Bp, int const [] Bj, unsigned int const [] Bx, 
        int [] Cp, int [] Cj, unsigned int [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long const [] Ax, int const [] Bp, int const [] Bj, long long const [] Bx, 
        int [] Cp, int [] Cj, long long [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned long long const [] Bx, int [] Cp, int [] Cj, unsigned long long [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        float const [] Ax, int const [] Bp, int const [] Bj, float const [] Bx, 
        int [] Cp, int [] Cj, float [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        double const [] Ax, int const [] Bp, int const [] Bj, double const [] Bx, 
        int [] Cp, int [] Cj, double [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double const [] Ax, int const [] Bp, int const [] Bj, long double const [] Bx, 
        int [] Cp, int [] Cj, long double [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cfloat_wrapper const [] Bx, int [] Cp, int [] Cj, npy_cfloat_wrapper [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_cdouble_wrapper [] Cx)
    bsr_eldiv_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_clongdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_clongdouble_wrapper [] Cx)
    """
  return _bsr.bsr_eldiv_bsr(*args)

def bsr_plus_bsr(*args):
  """
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_bool_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char const [] Ax, int const [] Bp, int const [] Bj, signed char const [] Bx, 
        int [] Cp, int [] Cj, signed char [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char const [] Ax, int const [] Bp, int const [] Bj, unsigned char const [] Bx, 
        int [] Cp, int [] Cj, unsigned char [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        short const [] Ax, int const [] Bp, int const [] Bj, short const [] Bx, 
        int [] Cp, int [] Cj, short [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned short const [] Bx, int [] Cp, int [] Cj, unsigned short [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        int const [] Ax, int const [] Bp, int const [] Bj, int const [] Bx, 
        int [] Cp, int [] Cj, int [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int const [] Ax, int const [] Bp, int const [] Bj, unsigned int const [] Bx, 
        int [] Cp, int [] Cj, unsigned int [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long const [] Ax, int const [] Bp, int const [] Bj, long long const [] Bx, 
        int [] Cp, int [] Cj, long long [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned long long const [] Bx, int [] Cp, int [] Cj, unsigned long long [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        float const [] Ax, int const [] Bp, int const [] Bj, float const [] Bx, 
        int [] Cp, int [] Cj, float [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        double const [] Ax, int const [] Bp, int const [] Bj, double const [] Bx, 
        int [] Cp, int [] Cj, double [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double const [] Ax, int const [] Bp, int const [] Bj, long double const [] Bx, 
        int [] Cp, int [] Cj, long double [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cfloat_wrapper const [] Bx, int [] Cp, int [] Cj, npy_cfloat_wrapper [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_cdouble_wrapper [] Cx)
    bsr_plus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_clongdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_clongdouble_wrapper [] Cx)
    """
  return _bsr.bsr_plus_bsr(*args)

def bsr_minus_bsr(*args):
  """
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_bool_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char const [] Ax, int const [] Bp, int const [] Bj, signed char const [] Bx, 
        int [] Cp, int [] Cj, signed char [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char const [] Ax, int const [] Bp, int const [] Bj, unsigned char const [] Bx, 
        int [] Cp, int [] Cj, unsigned char [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        short const [] Ax, int const [] Bp, int const [] Bj, short const [] Bx, 
        int [] Cp, int [] Cj, short [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned short const [] Bx, int [] Cp, int [] Cj, unsigned short [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        int const [] Ax, int const [] Bp, int const [] Bj, int const [] Bx, 
        int [] Cp, int [] Cj, int [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int const [] Ax, int const [] Bp, int const [] Bj, unsigned int const [] Bx, 
        int [] Cp, int [] Cj, unsigned int [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long const [] Ax, int const [] Bp, int const [] Bj, long long const [] Bx, 
        int [] Cp, int [] Cj, long long [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned long long const [] Bx, int [] Cp, int [] Cj, unsigned long long [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        float const [] Ax, int const [] Bp, int const [] Bj, float const [] Bx, 
        int [] Cp, int [] Cj, float [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        double const [] Ax, int const [] Bp, int const [] Bj, double const [] Bx, 
        int [] Cp, int [] Cj, double [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double const [] Ax, int const [] Bp, int const [] Bj, long double const [] Bx, 
        int [] Cp, int [] Cj, long double [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cfloat_wrapper const [] Bx, int [] Cp, int [] Cj, npy_cfloat_wrapper [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_cdouble_wrapper [] Cx)
    bsr_minus_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_clongdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_clongdouble_wrapper [] Cx)
    """
  return _bsr.bsr_minus_bsr(*args)

def bsr_sort_indices(*args):
  """
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        npy_bool_wrapper [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        signed char [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        unsigned char [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        short [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        unsigned short [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        int [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        unsigned int [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        long long [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        unsigned long long [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        float [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        double [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        long double [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        npy_cfloat_wrapper [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        npy_cdouble_wrapper [] Ax)
    bsr_sort_indices(int const n_brow, int const n_bcol, int const R, int const C, int [] Ap, int [] Aj, 
        npy_clongdouble_wrapper [] Ax)
    """
  return _bsr.bsr_sort_indices(*args)

def bsr_ne_bsr(*args):
  """
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_bool_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char const [] Ax, int const [] Bp, int const [] Bj, signed char const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char const [] Ax, int const [] Bp, int const [] Bj, unsigned char const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        short const [] Ax, int const [] Bp, int const [] Bj, short const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned short const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        int const [] Ax, int const [] Bp, int const [] Bj, int const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int const [] Ax, int const [] Bp, int const [] Bj, unsigned int const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long const [] Ax, int const [] Bp, int const [] Bj, long long const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned long long const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        float const [] Ax, int const [] Bp, int const [] Bj, float const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        double const [] Ax, int const [] Bp, int const [] Bj, double const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double const [] Ax, int const [] Bp, int const [] Bj, long double const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cfloat_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ne_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_clongdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    """
  return _bsr.bsr_ne_bsr(*args)

def bsr_lt_bsr(*args):
  """
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_bool_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char const [] Ax, int const [] Bp, int const [] Bj, signed char const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char const [] Ax, int const [] Bp, int const [] Bj, unsigned char const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        short const [] Ax, int const [] Bp, int const [] Bj, short const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned short const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        int const [] Ax, int const [] Bp, int const [] Bj, int const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int const [] Ax, int const [] Bp, int const [] Bj, unsigned int const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long const [] Ax, int const [] Bp, int const [] Bj, long long const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned long long const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        float const [] Ax, int const [] Bp, int const [] Bj, float const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        double const [] Ax, int const [] Bp, int const [] Bj, double const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double const [] Ax, int const [] Bp, int const [] Bj, long double const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cfloat_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_lt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_clongdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    """
  return _bsr.bsr_lt_bsr(*args)

def bsr_gt_bsr(*args):
  """
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_bool_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char const [] Ax, int const [] Bp, int const [] Bj, signed char const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char const [] Ax, int const [] Bp, int const [] Bj, unsigned char const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        short const [] Ax, int const [] Bp, int const [] Bj, short const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned short const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        int const [] Ax, int const [] Bp, int const [] Bj, int const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int const [] Ax, int const [] Bp, int const [] Bj, unsigned int const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long const [] Ax, int const [] Bp, int const [] Bj, long long const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned long long const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        float const [] Ax, int const [] Bp, int const [] Bj, float const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        double const [] Ax, int const [] Bp, int const [] Bj, double const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double const [] Ax, int const [] Bp, int const [] Bj, long double const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cfloat_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_gt_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_clongdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    """
  return _bsr.bsr_gt_bsr(*args)

def bsr_le_bsr(*args):
  """
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_bool_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char const [] Ax, int const [] Bp, int const [] Bj, signed char const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char const [] Ax, int const [] Bp, int const [] Bj, unsigned char const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        short const [] Ax, int const [] Bp, int const [] Bj, short const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned short const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        int const [] Ax, int const [] Bp, int const [] Bj, int const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int const [] Ax, int const [] Bp, int const [] Bj, unsigned int const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long const [] Ax, int const [] Bp, int const [] Bj, long long const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned long long const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        float const [] Ax, int const [] Bp, int const [] Bj, float const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        double const [] Ax, int const [] Bp, int const [] Bj, double const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double const [] Ax, int const [] Bp, int const [] Bj, long double const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cfloat_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_le_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_clongdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    """
  return _bsr.bsr_le_bsr(*args)

def bsr_ge_bsr(*args):
  """
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_bool_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_bool_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        signed char const [] Ax, int const [] Bp, int const [] Bj, signed char const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned char const [] Ax, int const [] Bp, int const [] Bj, unsigned char const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        short const [] Ax, int const [] Bp, int const [] Bj, short const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned short const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned short const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        int const [] Ax, int const [] Bp, int const [] Bj, int const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned int const [] Ax, int const [] Bp, int const [] Bj, unsigned int const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long long const [] Ax, int const [] Bp, int const [] Bj, long long const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        unsigned long long const [] Ax, int const [] Bp, int const [] Bj, 
        unsigned long long const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        float const [] Ax, int const [] Bp, int const [] Bj, float const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        double const [] Ax, int const [] Bp, int const [] Bj, double const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        long double const [] Ax, int const [] Bp, int const [] Bj, long double const [] Bx, 
        int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cfloat_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cfloat_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_cdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_cdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    bsr_ge_bsr(int const n_row, int const n_col, int const R, int const C, int const [] Ap, int const [] Aj, 
        npy_clongdouble_wrapper const [] Ax, int const [] Bp, int const [] Bj, 
        npy_clongdouble_wrapper const [] Bx, int [] Cp, int [] Cj, npy_bool_wrapper [] Cx)
    """
  return _bsr.bsr_ge_bsr(*args)
# This file is compatible with both classic and new-style classes.


