# Last Change: Wed Mar 05 09:00 PM 2008 J
# vim:syntax=python
from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)

for fmt in ['csr','csc','coo','bsr','dia']:
    sources = [ fmt + '_wrap.cxx' ]
    env.NumpyPythonExtension('_%s' % fmt, source = sources)
