# Last Change: Wed Mar 05 09:00 PM 2008 J
# vim:syntax=python
from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)
env.PrependUnique(CPPDEFINES = '__STDC_FORMAT_MACROS')

for fmt in ['csr','csc','coo','bsr','dia', 'csgraph']:
    sources = [ fmt + '_wrap.cxx' ]
    env.NumpyPythonExtension('_%s' % fmt, source = sources)
