# Last Change: Wed Mar 05 09:00 PM 2008 J
# vim:syntax=python
from numpy.distutils.misc_util import get_numpy_include_dirs
from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)

env.AppendUnique(CPPPATH = get_numpy_include_dirs())

for fmt in ['csr','csc','coo','bsr','dia']:
    sources = [ fmt + '_wrap.cxx' ]
    env.NumpyPythonExtension('_%s' % fmt, source = sources)
