from __future__ import annotations

from typing import (
    Callable,
    overload,
    Literal,
)

from ._ufuncs import psi
from numpy import sinc as sinc

from numpy.typing import ArrayLike, NDArray

from scipy._lib._util import DecimalNumber, IntNumber

_ComplexNumber = DecimalNumber | complex

_PointsDerivate = tuple[NDArray, NDArray]
_ZerosOrder = tuple[NDArray, NDArray, NDArray, NDArray]

__all__ = [
    "ai_zeros",
    "assoc_laguerre",
    "bei_zeros",
    "beip_zeros",
    "ber_zeros",
    "bernoulli",
    "berp_zeros",
    "bi_zeros",
    "clpmn",
    "comb",
    "digamma",
    "diric",
    "erf_zeros",
    "euler",
    "factorial",
    "factorial2",
    "factorialk",
    "fresnel_zeros",
    "fresnelc_zeros",
    "fresnels_zeros",
    "h1vp",
    "h2vp",
    "ivp",
    "jn_zeros",
    "jnjnp_zeros",
    "jnp_zeros",
    "jnyn_zeros",
    "jvp",
    "kei_zeros",
    "keip_zeros",
    "kelvin_zeros",
    "ker_zeros",
    "kerp_zeros",
    "kvp",
    "lmbda",
    "lpmn",
    "lpn",
    "lqmn",
    "lqn",
    "mathieu_even_coef",
    "mathieu_odd_coef",
    "obl_cv_seq",
    "pbdn_seq",
    "pbdv_seq",
    "pbvv_seq",
    "perm",
    "polygamma",
    "pro_cv_seq",
    "riccati_jn",
    "riccati_yn",
    "sinc",
    "stirling2",
    "y0_zeros",
    "y1_zeros",
    "y1p_zeros",
    "yn_zeros",
    "ynp_zeros",
    "yvp",
    "zeta",
]

_FACTORIALK_LIMITS_64BITS: dict[int, int]
_FACTORIALK_LIMITS_32BITS: dict[int, int]

digamma = psi

def diric(x: ArrayLike, n: ArrayLike) -> NDArray: ...
def jnjnp_zeros(nt: int) -> _ZerosOrder: ...
def jnyn_zeros(n: int, nt: int) -> _ZerosOrder: ...
def jn_zeros(n: int, nt: int) -> NDArray: ...
def jnp_zeros(n: int, nt: int) -> NDArray: ...
def yn_zeros(n: int, nt: int) -> NDArray: ...
def ynp_zeros(n: int, nt: int) -> NDArray: ...
def y0_zeros(nt: int, complex: bool = ...) -> _PointsDerivate: ...
def y1_zeros(nt: int, complex: bool = ...) -> _PointsDerivate: ...
def y1p_zeros(nt: int, complex: bool = ...) -> _PointsDerivate: ...
@overload
def jvp(v: ArrayLike, z: _ComplexNumber | ArrayLike, n: int = ...) -> NDArray: ...
@overload
def jvp(v: DecimalNumber, z: _ComplexNumber, n: int = ...) -> float: ...
@overload
def yvp(v: ArrayLike, z: ArrayLike, n: int = ...) -> NDArray: ...
@overload
def yvp(v: DecimalNumber, z: _ComplexNumber, n: int = ...) -> float: ...
@overload
def kvp(v: DecimalNumber, z: _ComplexNumber, n: int = ...) -> float: ...
@overload
def kvp(v: ArrayLike, z: ArrayLike, n: int = ...) -> NDArray: ...
@overload
def ivp(v: ArrayLike, z: ArrayLike, n: int = ...) -> NDArray: ...
@overload
def ivp(v: DecimalNumber, z: _ComplexNumber, n: int = ...) -> float: ...
@overload
def h1vp(v: ArrayLike, z: ArrayLike, n: int = ...) -> NDArray: ...
@overload
def h1vp(v: DecimalNumber, z: _ComplexNumber, n: int = ...) -> complex: ...
@overload
def h2vp(v: ArrayLike, z: ArrayLike, n: int = ...) -> NDArray: ...
@overload
def h2vp(v: DecimalNumber, z: _ComplexNumber, n: int = ...) -> complex: ...
def riccati_jn(n: int, x: float) -> _PointsDerivate: ...
def riccati_yn(n: int, x: float) -> _PointsDerivate: ...
def erf_zeros(nt: int) -> NDArray: ...
def fresnelc_zeros(nt: int) -> NDArray: ...
def fresnels_zeros(nt: int) -> NDArray: ...
def fresnel_zeros(nt: int) -> _PointsDerivate: ...
@overload
def assoc_laguerre(x: ArrayLike, n: int, k: float = ...) -> NDArray: ...
@overload
def assoc_laguerre(x: DecimalNumber, n: int, k: float = ...) -> float: ...
def polygamma(n: ArrayLike, x: ArrayLike) -> NDArray: ...
def mathieu_even_coef(m: int, q: DecimalNumber) -> NDArray: ...
def mathieu_odd_coef(m: int, q: DecimalNumber) -> NDArray: ...
def lpmn(m: DecimalNumber, n: DecimalNumber, z: ArrayLike) -> _PointsDerivate: ...
def clpmn(
    m: DecimalNumber, n: DecimalNumber, z: ArrayLike, type: Literal[2, 3] = ...
) -> _PointsDerivate: ...
def lqmn(m: IntNumber, n: IntNumber, z: ArrayLike) -> _PointsDerivate: ...
def bernoulli(n: int) -> NDArray: ...
def euler(n: int) -> NDArray: ...
def lpn(n: int, z: DecimalNumber) -> _PointsDerivate: ...
def lqn(n: int, z: DecimalNumber) -> _PointsDerivate: ...
def ai_zeros(nt: int) -> _ZerosOrder: ...
def bi_zeros(nt: int) -> _ZerosOrder: ...
def lmbda(v: int, x: int) -> _PointsDerivate: ...
def pbdv_seq(v: DecimalNumber, x: DecimalNumber) -> _PointsDerivate: ...
def pbvv_seq(v: DecimalNumber, x: DecimalNumber) -> _PointsDerivate: ...
def pbdn_seq(n: int, z: _ComplexNumber) -> _PointsDerivate: ...
def ber_zeros(nt: DecimalNumber) -> NDArray: ...
def bei_zeros(nt: DecimalNumber) -> NDArray: ...
def ker_zeros(nt: DecimalNumber) -> NDArray: ...
def kei_zeros(nt: DecimalNumber) -> NDArray: ...
def berp_zeros(nt: DecimalNumber) -> NDArray: ...
def beip_zeros(nt: DecimalNumber) -> NDArray: ...
def kerp_zeros(nt: DecimalNumber) -> NDArray: ...
def keip_zeros(nt: DecimalNumber) -> NDArray: ...
def kelvin_zeros(
    nt: DecimalNumber,
) -> tuple[
    NDArray,
    NDArray,
    NDArray,
    NDArray,
    NDArray,
    NDArray,
    NDArray,
    NDArray,
]: ...
def pro_cv_seq(m: IntNumber, n: IntNumber, c: DecimalNumber) -> NDArray: ...
def obl_cv_seq(m: IntNumber, n: IntNumber, c: DecimalNumber) -> NDArray: ...
@overload
def comb(
    N: ArrayLike,
    k: ArrayLike,
    *,
    exact: bool = ...,
    repetition: bool = ...,
) -> NDArray: ...
@overload
def comb(
    N: DecimalNumber,
    k: DecimalNumber,
    *,
    exact: Literal[True] = ...,
    repetition: bool = ...,
) -> IntNumber: ...
def comb(
    N: DecimalNumber,
    k: DecimalNumber,
    *,
    exact: bool = ...,
    repetition: bool = ...,
) -> float: ...
@overload
def perm(N: DecimalNumber, k: DecimalNumber, exact: bool = ...) -> IntNumber: ...
@overload
def perm(N: ArrayLike, k: ArrayLike, exact: bool = ...) -> NDArray: ...
@overload
def factorial(n: ArrayLike, exact: bool = ...) -> NDArray: ...
@overload
def factorial(n: DecimalNumber, exact: bool = ...) -> DecimalNumber: ...
@overload
def factorial2(n: ArrayLike, exact: bool = ...) -> NDArray: ...
@overload
def factorial2(n: IntNumber, exact: Literal[True]) -> int: ...
@overload
def factorial2(n: IntNumber, exact: bool = ...) -> NDArray: ...
@overload
def factorialk(n: IntNumber, k: IntNumber, exact: bool | None = ...) -> IntNumber: ...
@overload
def factorialk(n: ArrayLike, k: IntNumber, exact: bool | None = ...) -> NDArray: ...
@overload
def stirling2(N: ArrayLike, K: ArrayLike, *, exact: bool = ...) -> NDArray: ...
@overload
def stirling2(N: IntNumber, K: IntNumber, *, exact: bool = ...) -> DecimalNumber: ...
@overload
def zeta(
    x: DecimalNumber, q: DecimalNumber | None = ..., out: None = ...
) -> DecimalNumber: ...
@overload
def zeta(x: ArrayLike, q: ArrayLike, out: None | NDArray = ...) -> NDArray: ...

# Those are private methods
def _sph_harm_all(m: IntNumber, n: IntNumber, theta: ArrayLike, phi: ArrayLike) -> NDArray: ...
def _factorialx_approx_core(n: ArrayLike, k: int) -> NDArray: ...
def _factorialx_array_approx(n: ArrayLike, k: int) -> NDArray: ...
def _factorialx_array_exact(n: ArrayLike, k: int = ...) -> NDArray: ...
def _range_prod(lo: IntNumber, hi: IntNumber, k: IntNumber = ...) -> IntNumber: ...
def _nonneg_int_or_fail(n: IntNumber, var_name: str, strict: bool = ...) -> int: ...
@overload
def _bessel_diff_formula(
    v: ArrayLike,
    z: ArrayLike,
    n: int,
    L: Callable[[ArrayLike, ArrayLike], ArrayLike],
    phase: int,
) -> NDArray: ...
