from typing import Tuple

def _dd_exp(xhi: float, xlo: float) -> Tuple[float, float]: ...
def _dd_log(xhi: float, xlo: float) -> Tuple[float, float]: ...
def _dd_expm1(xhi: float, xlo: float) -> Tuple[float, float]: ...
