# Last Change: Mon Nov 26 03:00 PM 2007 J
# vim:syntax=python
from os.path import join as pjoin
import glob

from numpy.distutils.misc_util import get_numpy_include_dirs
from numpy.distutils.scons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)

env.AppendUnique(CPPPATH = get_numpy_include_dirs())
env.AppendUnique(CPPPATH = env['F2PYINCLUDEDIR'])

# XXX: implement fft checkers ...

# Build dfftpack
src = env.NumpyGlob(pjoin('dfftpack', '*.f'))
dfftpack = env.NumpyStaticExtLibrary('dfftpack', source = src)
env.AppendUnique(LIBS = ['dfftpack'])
env.AppendUnique(LIBPATH = env['build_dir'])

# Build _fftpack
src = ['src/zfft.c','src/drfft.c','src/zrfft.c', 'src/zfftnd.c']
wsrc = env.F2py(pjoin(env['build_dir'], '_fftpackmodule.c'),
                pjoin(env['build_dir'], 'fftpack.pyf'))
env.NumpyPythonExtension('_fftpack', source = src + wsrc)

# Build convolve
src = ['src/convolve.c']
wsrc = env.F2py(pjoin(env['build_dir'], 'convolve.pyf'))
env.NumpyPythonExtension('convolve', source = src + wsrc)
