# vim:syntax=python
from os.path import join as pjoin

from numscons import GetNumpyEnvironment, CheckF77Clib

env = GetNumpyEnvironment(ARGUMENTS)

env.NumpyPythonExtension('_shortest_path', source = ['_shortest_path.c'])
env.NumpyPythonExtension('_traversal', source = ['_traversal.c'])
env.NumpyPythonExtension('_min_spanning_tree', source = ['_min_spanning_tree.c'])
env.NumpyPythonExtension('_tools', source = ['_tools.c'])
