      SUBROUTINE DFFTF (N,R,WSAVE)
      IMPLICIT NONE
      INTEGER :: N
      DOUBLE PRECISION :: R(1), WSAVE(1)
      IF (N .EQ. 1) RETURN
      CALL DFFTF1 (N,R,WSAVE,WSAVE(N+1),WSAVE(2*N+1))
      RETURN
      END
