# Last Change: Thu Oct 18 09:00 PM 2007 J
# vim:syntax=python
from os.path import join

from numpy.distutils.misc_util import get_numpy_include_dirs
from numpy.distutils.scons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)

env.AppendUnique(CPPPATH = get_numpy_include_dirs())
env.AppendUnique(CPPPATH = 'src')

src = ["nd_image.c", "ni_filters.c", "ni_fourier.c", "ni_interpolation.c",
       "ni_measure.c", "ni_morphology.c", "ni_support.c"]

env.NumpyPythonExtension('_nd_image', source = [join('src', i) for i in src])
