# .github/dependabot.yml
# Dependabot configuration file
# See
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates

version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
      day: "friday"
      time: "15:00"
      timezone: "Asia/Shanghai"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: "weekly"
      day: "friday"
      time: "15:00"
      timezone: "Asia/Shanghai"


  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: "weekly"
      day: "friday"
      time: "15:00"
      timezone: "Asia/Shanghai"
