py3.install_sources([
    '__init__.py',
    'test__plotutils.py',
    'test__procrustes.py',
    'test_kdtree.py',
    'test_qhull.py',
    'test_slerp.py',
    'test_spherical_voronoi.py'
  ],
  subdir: 'scipy/spatial/tests',
  install_tag: 'tests'
)

py3.install_sources([
    'data/degenerate_pointset.npz',
    'data/selfdual-4d-polytope.txt'
  ],
  subdir: 'scipy/spatial/tests/data',
  install_tag: 'tests'
)
