      REAL FUNCTION WSDOT( N, SX, INCX, SY, INCY )
      INTEGER INCX, INCY, N
      REAL SX(*), SY(*)
      EXTERNAL SDOT
      REAL SDOT
      WSDOT = SDOT( N, SX, INCX, SY, INCY )
      END FUNCTION

      REAL FUNCTION WSDSDOT( N, SB, SX, INCX, SY, INCY )
      REAL SB
      INTEGER INCX, INCY, N
      REAL SX(*), SY(*)
      EXTERNAL SDSDOT
      REAL SDSDOT
      WSDSDOT = SDSDOT( N, SB, SX, INCX, SY, INCY )
      END FUNCTION

      REAL FUNCTION WSASUM( N, SX, INCX )
      INTEGER INCX, N
      REAL SX(*)
      EXTERNAL SASUM
      REAL SASUM
      WSASUM = SASUM( N, SX, INCX )
      END FUNCTION

      REAL FUNCTION WSNRM2( N, SX, INCX )
      INTEGER INCX, N
      REAL SX(*)
      EXTERNAL SNRM2
      REAL SNRM2
      WSNRM2 = SNRM2( N, SX, INCX )
      END FUNCTION

      REAL FUNCTION WSCASUM( N, CX, INCX )
      INTEGER INCX, N
      COMPLEX CX(*)
      EXTERNAL SCASUM
      REAL SCASUM
      WSCASUM = SCASUM( N, CX, INCX )
      END FUNCTION

      REAL FUNCTION WSCNRM2( N, CX, INCX )
      INTEGER INCX, N
      COMPLEX CX(*)
      EXTERNAL SCNRM2
      REAL SCNRM2
      WSCNRM2 = SCNRM2( N, CX, INCX )
      END FUNCTION

      COMPLEX FUNCTION WCDOTC( N, CX, INCX, CY, INCY )
      INTEGER INCX, INCY, N
      COMPLEX CX(*), CY(*)
      EXTERNAL CDOTC
      COMPLEX CDOTC
      WCDOTC = CDOTC( N, CX, INCX, CY, INCY )
      END FUNCTION

      COMPLEX FUNCTION WCDOTU( N, CX, INCX, CY, INCY )
      INTEGER INCX, INCY, N
      COMPLEX CX(*), CY(*)
      EXTERNAL CDOTU
      COMPLEX CDOTU
      WCDOTU = CDOTU( N, CX, INCX, CY, INCY )
      END FUNCTION

      DOUBLE COMPLEX FUNCTION WZDOTC( N, CX, INCX, CY, INCY )
      INTEGER INCX, INCY, N
      DOUBLE COMPLEX CX(*), CY(*)
      EXTERNAL ZDOTC
      DOUBLE COMPLEX ZDOTC
      WZDOTC = ZDOTC( N, CX, INCX, CY, INCY )
      END FUNCTION

      DOUBLE COMPLEX FUNCTION WZDOTU( N, CX, INCX, CY, INCY )
      INTEGER INCX, INCY, N
      DOUBLE COMPLEX CX(*), CY(*)
      EXTERNAL ZDOTU
      DOUBLE COMPLEX ZDOTU
      WZDOTU = ZDOTU( N, CX, INCX, CY, INCY )
      END FUNCTION
