iDate: Tue, 12 Feb 2002 09:34:30 -0800
From: Tami Dominick <dominick2@llnl.gov>
To: Lila Chase <chase3@llnl.gov>
Subject: Release CODE
Parts/Attachments:
   1.1   OK      34 lines  Text
   1.2 Shown     52 lines  Text
   2     OK     8.4 KB     Application
----------------------------------------


    [ Part 1.1, Text/PLAIN  34 lines. ]
    [ Not Shown. Use the "V" command to view or save this part. ]


      I have a Unlimited release for your code.


      UCRL-CODE-2002-018

      PYGIST/GIST3D

      Version 1.5

      Chase, L et al


      Your code has been given a Unlimited Distribution.


      Please forward a copy of the code, as soon as possible, on CD
      rom for our archival records and ESTSC.


      You will need to add the Notice 1 statement to your software,
      see attachment.

      --
      ~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*
      Mary E. Nijhuis
      Document Coordinator
      Document Approval and Report Services
      Technical Information Department
      Phone:  (925) 424-4008
      Email:  nijhuis2@llnl.gov
      Fax:  (925) 422-9115
      Website:  http://www-r.llnl.gov/tid/dars/dars-home.html

      ~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*~*


