# Last Change: Wed Mar 05 09:00 PM 2008 J
# vim:syntax=python
from os.path import join

from numpy.distutils.misc_util import get_numpy_include_dirs
from numscons import GetNumpyEnvironment

env = GetNumpyEnvironment(ARGUMENTS)

env.AppendUnique(CPPPATH = get_numpy_include_dirs())

env.NumpyPythonExtension('_sparsetools', 
                         source = [join('sparsetools', 'sparsetools_wrap.cxx')])

# Copy this python file into the distutils lib dir
env.Command(join(env['distutils_installdir'], 'sparsetools.py'),
            join(env['src_dir'], 'sparsetools', 'sparsetools.py'),
            Copy('$TARGET', '$SOURCE'))
