py3.install_sources([
    '__init__.py',
    'test_byteordercodes.py',
    'test_mio.py',
    'test_mio5_utils.py',
    'test_mio_funcs.py',
    'test_mio_utils.py',
    'test_miobase.py',
    'test_pathological.py',
    'test_streams.py'
  ],
  subdir: 'scipy/io/matlab/tests',
  install_tag: 'tests'
)

subdir('ref')
