name: Build Docker images 

on:
  push: 
    branches:
      - master
    tags:
      - '*'

jobs: 
  build:
    name: Build Docker image 
    runs-on: ubuntu-latest
    environment: scipy-dev
    if: "github.repository_owner == 'scipy' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip github]')"
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Lint Docker 
        uses: brpaz/hadolint-action@v1.2.1
        with: 
          dockerfile: ./tools/docker_dev/Dockerfile
      - name: Get refs
        shell: bash
        run: |
          export raw_branch=${GITHUB_REF#refs/heads/}
          echo "::set-output name=branch::${raw_branch//\//-}"
          echo "::set-output name=date::$(date +'%Y%m%d')"
          echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        id: getrefs
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "./tools/docker_dev"
          file: "./tools/docker_dev/Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            scipy/scipy-dev:${{ steps.getrefs.outputs.date }}-${{ steps.getrefs.outputs.branch}}-${{ steps.getrefs.outputs.sha8 }}, scipy/scipy-dev:latest