name: Build Docker Image

# Triggered only if environment.yml in main changes
# Pushes a Docker image with all dev dependencies to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - "environment.yml"

permissions:
   contents: read  # to fetch code (actions/checkout)

jobs:
  build-base-docker:
    name: Build base Docker image
    runs-on: ubuntu-latest
    # note this is the GH environment (where the Docker token is stored)
    environment: scipy-dev
    if: "github.repository_owner == 'scipy' && !contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip github]')"
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Lint Docker
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: ./tools/docker_dev/meson.Dockerfile

      - name: Get refs
        shell: bash
        run: |
          export raw_branch=${GITHUB_REF#refs/heads/}
          echo "branch=${raw_branch//\//-}" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
        id: getrefs

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: "."
          file: "./tools/docker_dev/meson.Dockerfile"
          push: ${{ github.event_name != 'pull_request' }}
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            scipy/scipy-dev:${{ steps.getrefs.outputs.date }}-${{ steps.getrefs.outputs.branch}}-${{ steps.getrefs.outputs.sha8 }}
            scipy/scipy-dev:latest

      - name: Image digest
        # Return details of the image build: sha and shell
        run: echo ${{ steps.docker_build.outputs.digest }}
