name: Emscripten/Pyodide

on:
  push:
    branches:
      - main
      - maintenance/**
  pull_request:
    branches:
      - main
      - maintenance/**
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  CCACHE_DIR: "${{ github.workspace }}/.ccache"
  CCACHE_MAXSIZE: "300M"

jobs:
  get_commit_message:
    name: Get commit message
    uses: ./.github/workflows/commit_message.yml

  build_wasm:
    name: Build & test SciPy for Pyodide
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'scipy/scipy' || github.repository == '')
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install ccache
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache

      - name: Set up ccache
        uses: ./.github/ccache
        with:
          workflow_name: ${{ github.workflow }}
          job_name: ${{ github.job }}

      - uses: pypa/cibuildwheel@4726cd35bb13f7bde50cf2761f2499ac7b3aa32c # v4.1.1
        env:
          CIBW_PLATFORM: pyodide
          CIBW_BUILD: cp314-pyodide_wasm32
          CIBW_BUILD_VERBOSITY: 1
          EM_COMPILER_WRAPPER: ccache
          CCACHE_COMPILERCHECK: "%compiler% --version"

      - name: Ccache performance
        run: |
          ccache --evict-older-than 1d
          ccache -s
