name: "Issue Labeler"
on:
  issues:
    types: [opened]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  label_issue:
    name: "Label Issue"
    # Permissions needed for labelling issues automatically
    # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
    permissions:
      contents: read
      issues: write  # needed to apply label
    runs-on: ubuntu-latest
    steps:
    # label based on issue title
    - uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # v3.4
      if: github.repository == 'scipy/scipy'
      with:
        configuration-path: .github/label-title.yml
        include-title: 1
        include-body: 0
        enable-versioned-regex: 0
        repo-token: ${{ secrets.GITHUB_TOKEN }}
