name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened]

jobs:

  triage_file_extensions:
    runs-on: ubuntu-latest
    steps:
    - uses: thomasjpfan/labeler@v2.5.0
      continue-on-error: true
      if: github.repository == 'scipy/scipy'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/labeler-file-extensions.yml"