name: Lint

on:
  push:
    branches:
      - maintenance/**
  pull_request:
    branches:
      - main
      - maintenance/**

permissions:
  contents: read # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test_lint:
    name: Lint
    # If using act to run CI locally the github object does not exist and the usual skipping should not be enforced
    if: "github.repository == 'scipy/scipy' || github.repository == ''"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # previous commits used in tools/lint.py
          submodules: recursive

      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          pixi-version: v0.55.0
          cache: false
          environments: lint

      - name: Spin Lint
        run: |
          set -euo pipefail
          pixi run lint --diff-against origin/$GITHUB_BASE_REF

      - name: Check that Python.h is first in any file including it.
        shell: bash
        run: pixi run check-python-h

      - name: Check module interdependencies
        working-directory: .github/workflows
        run: pixi run tach-check

      - name: Check external dependencies
        working-directory: .github/workflows
        run: pixi run tach-check-external
