name: BLAS tests (Linux)

# This file is meant for testing LP64/ILP64 BLAS/LAPACK flavors and build
# options on Linux. All other yml files for Linux will only test LP64 BLAS/LAPACK flavors.
#
# Jobs and their purpose:
#
#   - mkl:
#         Tests MKL installed from conda-forge in
#         2 ways: both LP64 and ILP64 via pkg-config.
#
#    - scipy-openblas64:
#         Tests ILP64-enabled build with scipy-openblas64.
#         Note that scipy-openblas32 is tested in other workflows.
#

on:
  pull_request:
    branches:
      - main
      - maintenance/**

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  get_commit_message:
    name: Get commit message
    uses: ./.github/workflows/commit_message.yml

  mkl-lp64:
    runs-on: ubuntu-latest
    name: "MKL LP64"
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'scipy/scipy' || github.repository == '')
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1
        with:
          pixi-version: v0.70.1
          cache: false

      - name: Build with defaults (LP64)
        run: |
          pixi run --environment=build-mkl-lp64 pkg-config --libs mkl-dynamic-lp64-seq  # check link flags
          pixi run build-mkl-lp64
          pixi run check-mkl-lp64-sharedlibs

      - name: Test
        run: pixi run --skip-deps test-mkl-lp64

  mkl-ilp64:
    runs-on: ubuntu-latest
    name: "MKL ILP64 (cython-blas LP64)"
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'scipy/scipy' || github.repository == '')
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1
        with:
          pixi-version: v0.70.1
          cache: false

      - name: Build with ILP64, cython-blas LP64
        run: |
          # Note: the `lp64` in the .pc name isn't a mistake, due to cython-blas-abi=lp64
          pixi run -e build-mkl-ilp64 pkg-config --libs mkl-dynamic-lp64-seq  # check link flags
          pixi run build-mkl-ilp64

      - name: Check shared libraries
        run: pixi run check-mkl-ilp64-sharedlibs

      - name: Test
        run: pixi run --skip-deps test-mkl-ilp64

  mkl-cyilp64:
    runs-on: ubuntu-latest
    name: "MKL ILP64 (cython-blas ILP64)"
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'scipy/scipy' || github.repository == '')
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1
        with:
          pixi-version: v0.70.1
          cache: false

      - name: Build with ILP64, cython-blas ILP64
        run: |
          pixi run -e build-mkl-ilp64 pkg-config --libs mkl-dynamic-ilp64-seq  # check link flags
          pixi run build-mkl-cyilp64

      - name: Check shared libraries
        run: pixi run check-mkl-cyilp64-sharedlibs

      - name: Test
        run: pixi run --skip-deps test-mkl-cyilp64

      - name: Install linalg ILP64 downstream test package
        # `spin run` needs build deps available
        shell: pixi run -e build-mkl-cyilp64 spin run --build-dir=build-mkl-cyilp64 bash -e {0}
        run: |
          pixi global install uv
          # `spin run` sets the system Python, so pass `--system`
          uv pip install --system --no-build-isolation -v -Csetup-args=--werror scipy/linalg/tests/_cython_examples/ilp64_test_package
      
      - name: Test linalg ILP64 downstream test package
        # `spin run` needs build deps available
        shell: pixi run -e build-mkl-cyilp64 spin run --build-dir=build-mkl-cyilp64 bash -e {0}
        run: |
          cp -r scipy/linalg/tests/_cython_examples/ilp64_test_package/tests /tmp/ilp64_tests
          cd /tmp
          uv pip install --system pytest
          python -m pytest ilp64_tests

  scipy-openblas-ilp64:
    runs-on: ubuntu-latest
    name: "scipy-openblas ILP64"
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'scipy/scipy' || github.repository == '')
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          fetch-depth: 0
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659 # v0.8.1
        with:
          pixi-version: v0.70.1
          cache: false

      - name: Build with ILP64
        run: pixi run build-scipy-openblas64

      - name: Test
        run: pixi run --skip-deps test-scipy-openblas64

      - name: Install linalg ILP64 downstream test package
        # `spin run` needs build deps available
        shell: pixi run -e scipy-openblas64 spin run --build-dir=build-scipy-openblas64 bash -e {0}
        run: |
          pixi global install uv
          # `spin run` sets the system Python, so pass `--system`
          uv pip install --system --no-build-isolation -v -Csetup-args=--werror scipy/linalg/tests/_cython_examples/ilp64_test_package

      - name: Test linalg ILP64 downstream test package
        shell: pixi run -e scipy-openblas64 spin run --build-dir=build-scipy-openblas64 bash -e {0}
        run: |
          cp -r scipy/linalg/tests/_cython_examples/ilp64_test_package/tests /tmp/ilp64_tests
          cd /tmp
          pytest ilp64_tests
