name: BLAS tests (Linux)

# This file is meant for testing LP64/ILP64 BLAS/LAPACK flavors and build
# options on Linux. All other yml files for Linux will only test LP64 BLAS/LAPACK flavors.
#
# Jobs and their purpose:
#
#   - mkl:
#         Tests MKL installed from PyPI (because easiest/fastest) in
#         2 ways: both LP64 and ILP64 via pkg-config.
#
#    - scipy-openblas64:
#         Tests ILP64-enabled build with scipy-openblas32 and scipy-openblas64.
#

on:
  pull_request:
    branches:
      - main
      - maintenance/**
  push:
    branches:
      - cyilp64-compile-test

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  get_commit_message:
    name: Get commit message
    uses: ./.github/workflows/commit_message.yml

  mkl-lp64:
    runs-on: ubuntu-latest
    name: "MKL LP64"
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'scipy/scipy' || github.repository == '')
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        fetch-depth: 0
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran

        pip install -r requirements/build.txt
        pip install mkl mkl-devel spin "click<8.3.0" pytest hypothesis pytest-xdist pooch

    - name: Build with defaults (LP64)
      run: |
        pkg-config --libs mkl-dynamic-lp64-seq  # check link flags
        spin build -S-Dblas=mkl-dynamic-lp64-seq

    - name: Test
      run: spin test -j4


  mkl-ilp64:
    runs-on: ubuntu-latest
    name: "MKL ILP64 (cython-blas LP64)"
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'scipy/scipy' || github.repository == '')
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      with:
        submodules: recursive
        fetch-depth: 0
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran

        pip install -r requirements/build.txt
        pip install mkl mkl-devel spin "click<8.3.0" pytest hypothesis pytest-xdist pooch

    - name: Build with ILP64
      run: |
        # Note: the `lp64` in the .pc name isn't a mistake, due to cython-blas-abi=lp64
        pkg-config --libs mkl-dynamic-lp64-seq  # check link flags
        spin build -S-Dblas=mkl-dynamic-lp64-seq -S-Duse-ilp64=true -S-Dcython-blas-abi=lp64

    - name: Test
      run: spin test -j4

  mkl-cyilp64:
    runs-on: ubuntu-latest
    name: "MKL ILP64 (cython-blas ILP64)"
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        fetch-depth: 0
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements/build.txt
        pip install mkl mkl-devel build pytest hypothesis pytest-xdist pooch

    - name: Build SciPy wheel and install
      run: |
        python -m build -wnx \
          -Csetup-args=-Dblas=mkl-dynamic-ilp64-seq \
          -Csetup-args=-Duse-ilp64=true \
          -Csetup-args=-D_without-fortran=true
        pip install dist/scipy*.whl

    - name: Test SciPy
      run: |
        cd /tmp
        python -m pytest --pyargs scipy -n4

    - name: Build and test ILP64 downstream package
      run: |
        pip install scipy/linalg/tests/_cython_examples/ilp64_test_package/
        cd /tmp
        python -m pytest --pyargs ilp64_test_package


  scipy-openblas-ilp64:
    runs-on: ubuntu-latest
    name: "scipy-openblas ILP64"
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        submodules: recursive
        fetch-depth: 0
        persist-credentials: false
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        pip install -r requirements/build.txt
        pip install build pytest hypothesis pytest-xdist pooch
        pip install -r requirements/openblas64.txt

    - name: Write out scipy-openblas64.pc
      run: |
        python -c'import scipy_openblas64 as so64; print(so64.get_pkg_config())' > scipy-openblas.pc

    - name: Build SciPy wheel and install
      run: |
        # scipy-openblas64 doesn't have LP64 symbols, so we can only use it
        # with `_without-fortran=true`. Drop this flag when `scipy.odr` gets
        # removed, keeping the rest of this job unchanged.
        export PKG_CONFIG_PATH=$PWD
        python -m build -wnx \
          -Csetup-args=-Dblas=scipy-openblas \
          -Csetup-args=-Duse-ilp64=true \
          -Csetup-args=-Dblas-symbol-suffix=64_ \
          -Csetup-args=-D_without-fortran=true
        pip install dist/scipy*.whl

    # TODO: move to end once this works
    - name: Build and test ILP64 downstream package
      run: |
        pip install scipy/linalg/tests/_cython_examples/ilp64_test_package/
        cd /tmp
        python -m pytest --pyargs ilp64_test_package

    - name: Test SciPy
      run: |
        cd /tmp
        python -m pytest --pyargs scipy -n4
