name: macOS tests

on:
  push:
    branches:
      - maintenance/**
  pull_request:
    branches:
      - main
      - maintenance/**

permissions:
  contents: read # to fetch code (actions/checkout)

env:
  INSTALLDIR: "build-install"
  CCACHE_MAXSIZE: "250M"
  CCACHE_DIR: "${{ github.workspace }}/.ccache"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  get_commit_message:
    name: Get commit message
    uses: ./.github/workflows/commit_message.yml

  test_meson:
    name: Conda & umfpack/scikit-sparse, fast, py3.12/npAny, spin
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'scipy/scipy' || github.repository == '')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          pixi-version: v0.65.0
          cache: false
          environments: py312-system-libs-osx

      - name: Set up ccache
        uses: ./.github/ccache
        with:
          workflow_name: ${{ github.workflow }}

      - name: Test SciPy
        shell: bash -l {0}
        run: |
          rm -rf ../../subprojects/boost_math  # so will fail if system boost doesn't work
          rm -rf ../../subprojects/qhull_r  # so will fail if system qhull doesn't work
          export OMP_NUM_THREADS=2
          pixi run test-system-libs -j2

      - name: Ccache statistics
        shell: bash -l {0}
        run: pixi exec ccache -s


  test_accelerate:
    name: Accelerate, full, py3.14/npAny, spin
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'scipy/scipy' || github.repository == '')
    runs-on: macos-15
    strategy:
      matrix:
        environment: [accelerate-lp64, accelerate-ilp64]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false

      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          pixi-version: v0.65.0
          cache: false
          environments: ${{ matrix.environment }}

      - name: Test SciPy
        # mpmath tests are too slow for CI
        run: pixi run test-${ENVIRONMENT} -m full -- -k "not mpmath"
        env:
          ENVIRONMENT: ${{ matrix.environment }}
