# A GitHub Action to demonstrate how to run SciPy on Python 3.13 before its release in Oct. 2024

name: scipy_on_py3_13
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  scipy_on_py3_13:
    strategy:
      fail-fast: false
      matrix:
        # https://docs.scipy.org/doc/scipy-1.13.0/building/index.html#building-from-source
        os: [ubuntu-latest]  # , macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
          allow-prereleases: true
      - if: runner.os == 'Linux'  # https://github.com/scipy/scipy/issues/16308#issuecomment-1140477372
        run: |
          sudo apt-get update -qq
          sudo apt-get install --yes libopenblas-dev
      - run: pip install --upgrade pip
      - run: pip install scipy
      # Some packages that depend on SciPy
      - run: pip install scikit-learn statsmodels xgboost
