# Workflow to build and test wheels.
# To work on the wheel building infrastructure on a fork, comment out:
#
# if: github.repository == 'scipy/scipy'
#
# All files related to wheel building are located
# at tools/wheels/

# The aim is to keep the workflow as close as possible to that of
# scipy/scipy-release.
name: Wheel builder


env:
  UV_VERSION: "0.12.5"


on:
  push:
    branches:
      - maintenance/**
  pull_request:
    branches:
      - main
      - maintenance/**
  workflow_dispatch:

permissions:
   contents: read  # to fetch code (actions/checkout)

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  get_commit_message:
    name: Get commit message
    uses: ./.github/workflows/commit_message.yml


  build_wheels:
    name: BLD > ${{ matrix.python }}-${{ matrix.buildplat[1] }}-${{ matrix.buildplat[2] }}-${{ matrix.buildplat[3] }}
    needs: get_commit_message
    if: >
      needs.get_commit_message.outputs.message == 1
    runs-on: ${{ matrix.buildplat[0] }}
    if: (github.repository == 'scipy/scipy' || github.repository == '')
    strategy:
      # Ensure that a wheel builder finishes even if another fails
      fail-fast: false
      matrix:
        # Github Actions doesn't support pairing matrix values together, let's improvise
        # https://github.com/github/feedback/discussions/7835#discussioncomment-1769026
        buildplat:
        # should also be able to do multi-archs on a single entry, e.g.
        # [windows-2025, win*, "AMD64 x86"]. However, those two require a different compiler setup
        # so easier to separate out here.
        - [ubuntu-24.04, manylinux, x86_64, "", ""]
        - [ubuntu-24.04, musllinux, x86_64, "", ""]
        - [ubuntu-24.04-arm, manylinux, aarch64, "", ""]
        - [ubuntu-24.04-arm, musllinux, aarch64, "", ""]
        - [macos-15-intel, macosx, x86_64, openblas, "10.15"]
        - [macos-15-intel, macosx, x86_64, accelerate, "14.0"]
        - [macos-14, macosx, arm64, openblas, "12.3"]
        - [macos-14, macosx, arm64, accelerate, "14.0"]
        - [windows-2025, win, AMD64, "", ""]
        - [windows-11-arm, win, ARM64, "", ""]
        python: ["cp312"]

    steps:
      - name: Checkout scipy
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
          persist-credentials: false

      # the version of python we'll run cibuildwheel with
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.13

      # Used in cibw_before_build to install pinned build dependencies
      # Note that cibuildwheel provides it in the Linux images, so this install
      # is only useful on macOS/windows
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          # can't use checksum here, because there are different packages
          # for different OS
          version: ${{ env.UV_VERSION }}
          enable-cache: false

      # create a lock file, to keep the workflow as close as possible to scipy-release
      - name: Create uv.lock
        run: | 
          uv lock --exclude-newer "7 days"

      - name: Setup windows
        if: matrix.buildplat[1] == 'win'
        run: |
          echo "CC=clang-cl" >> $env:GITHUB_ENV
          echo "CXX=clang-cl" >> $env:GITHUB_ENV
          echo "TARGET_ARCH=${{ matrix.buildplat[2] }}" >> $env:GITHUB_ENV
          
          # workaround for https://github.com/scipy/scipy/issues/25067
          rm -fo c:/Strawberry/c/lib/pkgconfig/*.pc
          
          # pkg-config setup
          $CIBW = "${{ github.workspace }}/.openblas"
          # pkgconfig needs a complete path, and not just "./openblas since the
          # build is run in a tmp dir (?)
          # It seems somewhere in the env passing, `\` is not
          # passed through, so convert it to '/'
          $CIBW = $CIBW.replace("\","/")
          echo "CIBW_ENVIRONMENT_WINDOWS=PKG_CONFIG_PATH=$CIBW" >> $env:GITHUB_ENV

      - name: Setup macOS
        if: startsWith( matrix.buildplat[0], 'macos-' )
        env:
          BLAS_VARIANT: ${{ matrix.buildplat[3] }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.buildplat[4] }}
        run: |
          if [[ "${BLAS_VARIANT}" == "accelerate" ]]; then
            echo CIBW_CONFIG_SETTINGS=\"setup-args=-Dblas=accelerate\" >> "$GITHUB_ENV"

            # Builds with Accelerate only target macOS>=14.0
            CIBW_ENV="CIBW_ENVIRONMENT_MACOS=MACOSX_DEPLOYMENT_TARGET=14.0 INSTALL_OPENBLAS=false"
          else
            CIBW_ENV="CIBW_ENVIRONMENT_MACOS=PKG_CONFIG_PATH=$PWD/.openblas \
              MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET}""
          fi
          echo "$CIBW_ENV" >> "$GITHUB_ENV"

      - name: Build wheels
        uses: pypa/cibuildwheel@1828c10ab37f080699c7b81cea34097c684a7074 # v4.2.0
        env:
          CIBW_BUILD: ${{ matrix.python }}-${{ matrix.buildplat[1] }}*
          CIBW_ARCHS: ${{ matrix.buildplat[2] }}
          CIBW_ENABLE: cpython-prerelease
        with:
          config-file: pyproject.toml
          output-dir: dist

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: ./dist/*.whl
          name: ${{ matrix.python }}-${{ matrix.buildplat[1] }}-${{ matrix.buildplat[2] }}-${{ matrix.buildplat[3] }}-${{ matrix.buildplat[4] }}
